### ISSUE TITLE
Verwendung wollen/möchten

### ISSUE THREAD

**Issue by Philipp-K** [phpbb-de/phpbb-translation#109]
Das sollte einmal auf Einheitlichkeit geprüft werden.
Siehe z. B. http://www.gutefrage.net/frage/was-ist-der-unterschied-zwischen-moechten-und-wollen

**Comment by Philipp-K** [comment]
Im Du-Paket:
- möchtest: 173 Vorkommen
- willst: 36 Vorkommen

Grundsätzlich ist wohl "möchtest" höflicher. Allerdings bei Formulierungen wie

> Bist du dir sicher, dass du die Datei-Statistik neu synchronisieren willst?

finde ich "willst" irgendwie schöner.

**Comment by gn36** [comment]
Spontan würde ich an so einer Stelle auch "willst" sagen. "Möchtest" geht aber auch sehr gut. Im "Du" Paket kann man in meinen Augen im Prinzip beides verwenden, im "Sie" Paket sollten wir finde ich aber höflich sein. Im Zuge der Einheitlichkeit würde ich daher alles in beiden Paketen auf "möchtest" umstellen.

**Comment by Philipp-K** [comment]
Ich bin die Vorkommen von wollen einmal durchgegangen und habe wollen durch möchten ersetzt.

**Comment by Philipp-K** [comment]
Passt dazu: http://ruthe.de/cartoon/2736/datum/asc/
