### ISSUE TITLE
Aktionen in den E-Mail-Tempaltes

### ISSUE THREAD

**Issue by Philipp-K** [phpbb-de/phpbb-translation#110]
Mir gefallen die Aktionen in den E-Mail-Templates nicht wirklich:

> Wenn Sie das Thema ansehen möchten, verwenden Sie folgenden Link:
> {U_TOPIC}

Vielleicht lässt sich da was anderes finden.

**Comment by Crizz0** [comment]
"Um das Thema zu besuchen, bitte folgenden Link anklicken"

"Zum Besuchen des Themas bitte folgenden Link auswählen"

**Comment by Philipp-K** [comment]
Ich würde da die Diskussion zu "Stellen Sie..." abwarten (https://www.phpbb.de/community/viewtopic.php?f=142&t=231509)

**Comment by Philipp-K** [comment]
Vorschlag:

> Sie können sich das Thema ansehen, wenn Sie folgenden Link aufrufen:

**Comment by nickvergessen** [comment]
klingt gut

**Comment by gn36** [comment]
Ja, sehe ich auch so.

**Comment by Philipp-K** [comment]
Bei Aktionen, die nicht optional sind, würde ich eine etwas andere Formulierung verwenden:

> Um das Benutzerkonto zu aktivieren, musst du folgenden Link aufrufen:
