### ISSUE TITLE
Typo: "selektriert"

### ISSUE THREAD

**Issue by bantu** [phpbb-de/phpbb-translation#112]
sollte wohl "selektiert" sein?

**Comment by Crizz0** [comment]
Siehe #113 

Ich habs korrigiert.

**Comment by Crizz0** [comment]
Betrifft auch phpBB 3.0: \phpBB-3.0.12-deutsch\phpBB3\language\de\acp\prune.php Zeile 43, gleicher Satz.

**Comment by gn36** [comment]
Möglicherweise sollten wir die [Diskussion](https://github.com/phpbb-de/phpbb-translation/pull/113) zur Änderung des "selektiert" hier weiterführen:
Mungo:

> Ich würde das eh in "ausgewählt werden" ändern. Wir verwenden sonst an keiner anderen Stelle "selektiert". Wäre aus meiner Sicht einheitlicher.

nickvergessen:

> Jop, denke auch.
> @Philipp-K Meinung?
