### ISSUE TITLE
"selektiert" -> "ausgewählt werden"? [acp/prune.php]

### ISSUE THREAD

**Issue by gn36** [phpbb-de/phpbb-translation#118]
Möglicherweise sollten wir die [Diskussion](https://github.com/phpbb-de/phpbb-translation/pull/113) zur Änderung des "selektiert" hier weiterführen:
Mungo:

> Ich würde das eh in "ausgewählt werden" ändern. Wir verwenden sonst an keiner anderen Stelle "selektiert". Wäre aus meiner Sicht einheitlicher.

nickvergessen:

> Jop, denke auch.
> @Philipp-K Meinung?

**Comment by Philipp-K** [comment]
Auswählen ist für mich die Auswahl einzelner Objekte über Checkboxen etc. Hier haben wir aber eine andere Konstellation: die Benutzer werden nach bestimmten Kriterien selektiert, die der Benutzer angibt.

Der Unterschied hat meiner Ansicht also nach schon seine Berechtigung

**Comment by Crizz0** [comment]
Ich finde das am logischsten:

"Benutzerkonten können anhand verschiedener Kriterien gefiltert werden:"

Denn man filtert die Anzeige der Benutzerkonten, die dann angezeigt werden. Oder nicht?

**Comment by Philipp-K** [comment]
Hier der vollständige Satz:

> Dieser Bereich erlaubt es dir, Benutzer deines Boards zu löschen oder zu deaktivieren. Benutzerkonten können anhand verschiedener Kriterien selektiert werden: der Beitragszahl, der letzten Aktivität usw. Die Kriterien können kombiniert werden, so dass du die betroffenen Benutzer weiter einschränken kannst. So kannst du z. B. Benutzer löschen, die weniger als 10 Beiträge haben und deren letzte Aktivität vor dem 2002-01-01 war. Bei Textfeldern kannst Du einen Stern (*) als Platzhalter verwenden. Alternativ kannst du die Kriterien auch überspringen, indem du eine Liste von Benutzernamen direkt in das Textfeld eingibst (jeden Benutzer in eine Zeile). Gehe vorsichtig mit diesem Tool um! Wenn ein Benutzer gelöscht ist, gibt es keine Funktion, um diesen Vorgang rückgängig zu machen.

**Comment by Philipp-K** [comment]
Mit filtern könnte ich noch leben - auch wenn mir selektieren weiterhin besser gefällt

**Comment by Crizz0** [comment]
Ich bin weiterhin für "gefiltert", das klingt noch am besten _imho_

**Comment by gn36** [comment]
Eigentlich sehe ich von der Bedeutung her keinen Unterschied zwischen "selektiert" und "ausgewählt". Ein User kann auch selber Personen aus einer Liste selektieren, wenn er die Personen anklickt. Ebenso kann er sie auswählen und tut dabei genau das gleiche. Wenn du einen Bedeutungsunterschied haben möchtest, dann solltest du "filtern" oder besser "automatisch auswählen/selektieren" nehmen. 

Ich habe die Funktion aber noch nicht ausprobiert: Bekommt man vor dem endgültigen Löschen noch eine Liste, in der man auswählen kann, oder sind die User, die den Filterkriterien entsprechen nach einer Bestätigung wie "Willst du diesen Vorgang ausführen?" direkt weg? Im ersten Fall bin ich für "ausgewählt", im zweiten für "automatisch ausgewählt". In beiden Fällen spricht aber nichts dagegen, "ausgewählt" gegen "selektiert" auszutauschen.

**Comment by Philipp-K** [comment]
> Bekommt man vor dem endgültigen Löschen noch eine Liste, in der man auswählen kann, oder sind die User, die den Filterkriterien entsprechen nach einer Bestätigung wie "Willst du diesen Vorgang ausführen?" direkt weg?

Erstes ist der Fall. Aber genau aus dem Grund passt meiner Ansicht nach zweimal auswählen nicht. Ggf. wäre noch vorselektieren denkbar - wobei du allerdings nur Benutzer entfernen und keine weitern hinzufügen kannst.

**Comment by gn36** [comment]
Ich habe nichts gegen "selektiert" - in meinen Augen ist das aber gleichbedeutend mit "ausgewählt", den von dir angestrebten Bedeutungsunterschied sehe ich da nicht. Wenn überall sonst "ausgewählt" steht, würde ich das ehrlich gesagt auch hier verwenden.
Wenn es dir um den Bedeutungsunterschied geht: "vorselektiert" hört sich besser an als "vorausgewählt", "gefiltert" würde aber besser passen.

Alternativ für den Satz:

> Benutzerkonten können anhand verschiedener Kriterien selektiert werden:

Würde auch das folgende passen:

> Die Eingrenzung der zu löschenden Benutzerkonten erfolgt anhand verschiedener Kriterien:

Wir könnten noch überlegen den Text um

> Nach der Filterung hast du die Möglichkeit, einzelne betroffene Benutzerkonten von der Löschung auszunehmen.

oder

> Nach der Filterung kannst du die zur Löschung vorgeschlagenen Benutzerkonten vor der endgültigen Löschung weiter eingrenzen.

oder etwas ähnliches ergänzen.

**Comment by Philipp-K** [comment]
Es ist halt ein zweistufiger Prozess - und da hätte ich dann schon zwei unterschiedliche Begriffe, die das mit der Zweistufigtkeit etwas verdeutlichen

**Comment by Philipp-K** [comment]
Wie wäre es mit dieser Variante, die das Problem umgeht:

> Dieser Bereich erlaubt es dir, Benutzer deines Boards zu löschen oder zu deaktivieren. Du kannst die zu löschenden bzw. zu deaktivierenden Benutzerkonten anhand verschiedener Kriterien festlegen: der Beitragszahl, der letzten Aktivität usw. Die Kriterien können kombiniert werden, so dass du die betroffenen Benutzer weiter einschränken kannst. So kannst du z. B. Benutzer löschen, die weniger als 10 Beiträge haben und deren letzte Aktivität vor dem 2002-01-01 war. Bei Textfeldern kannst Du einen Stern (*) als Platzhalter verwenden. Alternativ kannst du die Kriterien auch überspringen, indem du eine Liste von Benutzernamen direkt in das Textfeld eingibst (jeden Benutzer in eine Zeile). Gehe vorsichtig mit diesem Tool um! Wenn ein Benutzer gelöscht ist, gibt es keine Funktion, um diesen Vorgang rückgängig zu machen.

**Comment by Philipp-K** [comment]
Keine Meinungen dazu?

**Comment by gn36** [comment]
Abgesehen davon, dass ich das Datumsformat im Text ungünstig finde finde ich die Änderung so gut. Ich vermute mal, dass das daran liegt, dass es in diesem Format eingegeben werden muss.

**Comment by Philipp-K** [comment]
> Ich vermute mal, dass das daran liegt, dass es in diesem Format eingegeben werden muss.

Genau
