### ISSUE TITLE
Umsetzung "Stellen Sie..."

### ISSUE THREAD

**Issue by Philipp-K** [phpbb-de/phpbb-translation#121]
Siehe https://www.phpbb.de/community/viewtopic.php?f=142&t=231509

**Comment by Crizz0** [comment]
"Es wird keine Begrenzung festgelegt, wenn 0 als Wert eingestellt wird." 

Ist für mich eigentlich Favorit. Ich hab allerdings auch kein Problem mit "Damit keine Begrenzung festgelegt wird, stellen Sie 0 als Wert ein." und finde das persönlicher, da man den Benutzer anredet.

**Comment by Philipp-K** [comment]
Diskussionen bitte im Forum

**Comment by Philipp-K** [comment]
In #122 umgesetzt.
In ein paar wenigen Fällen habe ich die bisherige Formulierung belassen:
- 0 bedeutet unbegrenzt
- Bei einem Wert von 0 sind unbegrenzt viele Empfänger zulässig.
- Diese Funktion wird bei einem Wert von 0 deaktiviert. (als Warnung)
