### ISSUE TITLE
"Gehe zu" / Forennavigation

### ISSUE THREAD

**Issue by Philipp-K** [phpbb-de/phpbb-translation#143]
Die Beschreibung "Gehe zu" gefällt mir nicht wirklich. Hat jemand eine gute Alternative?
So auf die Schnelle fallen mir ein:
- Forum wechseln
- Andere Foren

**Comment by Crizz0** [comment]
Ich kenne das "Gehe zu" aus dem Notepad++ um zu den Zeilen zu kommen. "Springe zu"?

**Comment by Philipp-K** [comment]
Springe zu wäre auch eine gute Alternative

**Comment by nickvergessen** [comment]
Auf area51 wird derzeit diskutiert das in "Jump to forum" zu ändern

**Comment by Philipp-K** [comment]
Wäre dann ein Argument für "Forum wechseln"

**Comment by Philipp-K** [comment]
Machen wir "Forum wechseln" draus? Passt ja unabhängig der Entscheidung

**Comment by nickvergessen** [comment]
jo

**Comment by Crizz0** [comment]
Fände ich i.O.
