### ISSUE TITLE
ACP/MPC in der Kopfzeile

### ISSUE THREAD

**Issue by Philipp-K** [phpbb-de/phpbb-translation#144]
Was sollen wir für ACP/MCP in der Kopfzeile verwenden. Der Begriff sollte möglichst kurz sein.
ACP/MCP haben sich zwar auch in der deutschen phpBB-Community etabliert, bislang sind wir aber konsequent bei den (für den Zweck nun zu langen) Begriffen Administrations-/Moderations-Bereich geblieben, um eine konsistente deutschsprachige Übersetzung zu haben.

Grundsätzlich sollte das Problem auch bei anderen Sprachen existieren - wir sollten also schauen, wie diese damit umgehen.

**Comment by nickvergessen** [comment]
![too_long](https://cloud.githubusercontent.com/assets/213943/3586892/6fbdd1ee-0c34-11e4-9d8a-39508546ac37.png)
![short_enough](https://cloud.githubusercontent.com/assets/213943/3586891/6e47c46e-0c34-11e4-9fe6-419e9ef633f0.png)

**Comment by Crizz0** [comment]
Also die Holländer nutzen da einfach:
Administrieren
Admin

Fertig. Also entweder machen wir das genauso, wobei sich "Moderieren" doof abkürzen lässt oder ich bin einfach für ACP / MCP. Das wird im Support-Bereich oft genug benutzt, nicht immer verstanden, so aber mit Sicherheit salonfähiger.

**Comment by gn36** [comment]
Das Problem hast du doch so oder so, nickvergessen, wenn der Nickname etwas länger wird, oder? 

Sinnvolle Synonyme, die nicht mit einem krassen Bruch der bisherigen Übersetzung eingehen fallen mir aber nicht wirklich ein. "verwalten" würde z.B. noch halbwegs passen. Aber da das ACP nicht "Board Verwaltung" heißt ist das glaube ich auch nicht sehr verständlich.

Eventuell nehmen wir auch sowas wie "Adm." und "Mod." oder "Adm.-B." und "Mod.-B.". Dann würden wir bei der aktuellen Version bleiben und es halt tatsächlich einfach abkürzen.

**Comment by Philipp-K** [comment]
Falls jemand gerade etwas Luft hat: mich würde mal interessieren, wie das in der französischen Version übersetzt wurde. Die Franzosen sind ja meist sehr bedacht, die französische Variante zu nehmen und nicht die englische zu übernehmen.

**Comment by nickvergessen** [comment]
die links verschwinden im Extremfall jetzt immer, wir müssen also jetzt nichts mehr ändern

**Comment by LehrlingBeate** [comment]
Hallo,
die Franzosen verwenden "Panneau d’administration".
LG Beate

**Comment by Philipp-K** [comment]
@LehrlingBeate Auch in der Kurznavigation oben?
@all: Bleibt die Frage, ob wir "Administrieren" mit "Admin" abkürzen ("Mod finde ich allerdings weniger passend)

**Comment by LehrlingBeate** [comment]
nein, in der Kurznavigation steht PCA und PCM.

**Comment by gn36** [comment]
> die links verschwinden im Extremfall jetzt immer, wir müssen also jetzt nichts mehr ändern

Wegen dem Nickname oder gab es noch ne andere Änderung?

**Comment by LehrlingBeate** [comment]
nicht, dass ich mich jetzt wirklich einmischen will, aber mir geht es so, dass ich, wenn ich ein Problem habe und die englischen Begriffe in Google eingebe, in der Regel sofort fündig werde. Wenn ich aber eine deutsche Entsprechung eingebe, wird es schon schwieriger. Ich persönlich halte die Beibehaltung der englischen Originalbegriffe in den Bereichen IT, Computer etc. für sehr sinnvoll, einfach weil es für den Benutzer dann einfach ist, Hilfe zu finden. Allerdings kann ich auch Englisch. 
LG Beate

**Comment by nickvergessen** [comment]
@gn36 wegen langen Nicknamen und problemen bei kurzen Übersetzungen in russisch, niederländisch, deutsch, ....

**Comment by Crizz0** [comment]
Also kann das Issue geschlossen werden, wenn es egal ist. Richtig?

**Comment by Philipp-K** [comment]
Ich hab den Issue ja extra wieder aufgemacht, da noch die Frage offen war, ob wir "Administrieren" oder "Admin" verwenden sollen

**Comment by LehrlingBeate** [comment]
Hallo,
wenn man die Begriffe konsequent abkürzt, kommt man zu AB und MB, was mir persönlich gut gefallen würde. Ein paar Gedanken noch zu der Sache. Erstens werden nur die Moderatoren und die Administratoren diese Abkürzungen/Wörter sehen. Zweitens wird, wenn man mit der Maus drüberfährt, Administrations-Bereich bzw. Moderations-Bereich angezeigt. Drittens haben wir die Icons, die anzeigen, dass es hier zu einem "Arbeitsbereich" geht und viertens kann es doch gut sein, dass dort oben, sollten die User Erweiterungen einbauen, noch weitere Links untergebracht werden und es auch von daher günstig wäre, man würde sich für eine Abkürzung entscheiden. 
Und rein vom optischen Standpunkt aus betrachtet, würde eine Abkürzung auch besser passen, da links von diesen beiden Links die FAQ wären, also auch eine Abkürzung aus Großbuchstaben.
LG Beate

**Comment by gn36** [comment]
Also haben wir jetzt folgende Vorschläge:
- Adm. / Mod.
- AB / MB
- ACP / MCP
- Administrieren / Moderieren
- Adm.-B. / Mod.-B.
- Admin / Moderieren
- Admin / Mod

Die Liste ist nach meiner Präferenz sortiert, oben gefällt mir am besten.
(Admin/Moderieren nachträglich eingefügt)

**Comment by Philipp-K** [comment]
Die Variante
Admin / Moderieren
fehlt

**Comment by Crizz0** [comment]
Ich bin für:
ACP / MCP
danach
Adm. / Mod.

Der ist mMn irgendwie nicht tauglich, wenn es auch kurz sein soll und liegt mMn nicht immer so Nahe.

**Comment by Philipp-K** [comment]
Meine Rangfolge:
- Admin / Moderieren
- Admin / Mod
- Administrieren / Moderieren
- Adm. / Mod.
- Adm.-B. / Mod.-B.
- ACP / MCP
- AB / MB

ACP passt meiner Ansicht nach weiterhin nicht, da es der englische Begriff ist und sonst nirgends verwendet wird, auch AB wäre eine Wortneuschöpfung (und bei MB sogar zweideutig)

**Comment by nickvergessen** [comment]
Ich wäre für Adm. / Moderieren

**Comment by Philipp-K** [comment]
Die Varianten mit Adm... und Mod... sind wohl die, die sich für alle als tragbar erweisen. Fragt nur, ob/wo wir abkürzen:

A: Administrieren
B: Admin
C: Adm.

X: Moderieren
Y: Mod
Z: Mod.

Bringt die doch mal bitte in Eure Präferenzordnung.

Meine: B-C-A und X-Z-Y

**Comment by gn36** [comment]
C-A-B und Z-X-Y

**Comment by nickvergessen** [comment]
CAB XZY

**Comment by Crizz0** [comment]
CAB / ZXY

**Comment by gn36** [comment]
Brauchen wir wohl noch mindestens eine Meinung für ZXY vs XZY...

**Comment by Philipp-K** [comment]
Wenn wir Adm. nehmen, bin ich auch für Z
