### ISSUE TITLE
fehlerhaft / falsch

### ISSUE THREAD

**Issue by Philipp-K** [phpbb-de/phpbb-translation#147]
Ruft auch nach Vereinheitlichung

**Comment by Philipp-K** [comment]
Sollten wir auch noch für RC5 erledigen

**Comment by Crizz0** [comment]
da würde ic hder einfachheit halber nach "falsch" und "fehlerhaft" suchen und die wenigeren Treffer anpassen.

**Comment by Philipp-K** [comment]
Die Frage ist, ob falsch und fehlerhaft Synonyme sind oder ob es eben doch einen kleinen, feinen Unterschied gibt - ganz im Sinne:

> Das Vorgehen ist zwar nicht fehlerhaft, aber falsch

**Comment by Crizz0** [comment]
Also ich sehe hier kein "fehlerhaft" was nicht auch mit einem "falsch" ersetzt werden kann. Du?

>   H:\phpbbde-translation\phpbb-translation\language\de\acp\attachments.php (2 hits)
>     Line 80:    'CHECK_CONTENT_EXPLAIN'     => 'Manchen Browsern kann ein fehlerhafter MIME-Typ für hochgeladene Dateien vorgetäuscht werden. Diese Option stellt sicher, dass Dateien, die dieses Verhalten provozieren könnten, abgewiesen werden.',
>     Line 116:   'FILES_STATS_WRONG'     => 'Deine Datei-Statistik ist vermutlich fehlerhaft und muss resynchronisiert werden. Derzeitige Werte: Anzahl von Dateianhängen = %1$d, Gesamtgröße der Dateianhänge = %2$s.<br />%3$sDatei-Statistik resynchronisieren%4$s.',
>   H:\phpbbde-translation\phpbb-translation\language\de\acp\board.php (1 hit)
>     Line 452:   'ACP_SERVER_SETTINGS_EXPLAIN'   => 'Hier kannst du einige Einstellungen bezüglich Server und Domain vornehmen. Bitte stelle sicher, dass die Daten, die du eingibst, auch wirklich stimmen, denn fehlerhafte Angaben könnten zu E-Mails führen, die falsche Informationen enthalten. Wenn du den Domain-Namen eingibst, denk daran, dass http:// oder eine andere Protokoll-Bezeichnung darin enthalten ist. Ändere den Port nur, wenn du weißt, dass dein Server einen anderen Port nutzt; Port 80 ist in den allermeisten Fällen richtig.',
>   H:\phpbbde-translation\phpbb-translation\language\de\acp\common.php (4 hits)
>     Line 356:   'ERROR_MBSTRING_FUNC_OVERLOAD'                  => 'Das Überladen von Funktionen ist fehlerhaft konfiguriert',
>     Line 358:   'ERROR_MBSTRING_ENCODING_TRANSLATION'           => 'Die transparente Zeichenkodierung ist fehlerhaft konfiguriert',
>     Line 360:   'ERROR_MBSTRING_HTTP_INPUT'                     => 'Die HTTP-Eingabe-Kodierung ist fehlerhaft konfiguriert',
>     Line 362:   'ERROR_MBSTRING_HTTP_OUTPUT'                    => 'Die HTTP-Ausgabe-Kodierung ist fehlerhaft konfiguriert',
>   H:\phpbbde-translation\phpbb-translation\language\de\captcha_qa.php (1 hit)
>     Line 45:    'CONFIRM_QUESTION_WRONG'    => 'Du hast eine fehlerhafte Antwort auf die Frage angegeben.',
>   H:\phpbbde-translation\phpbb-translation\language\de\captcha_recaptcha.php (1 hit)
>     Line 46:    'RECAPTCHA_INCORRECT'           => 'Der von dir eingegebene Bestätigungscode ist fehlerhaft',
>   H:\phpbbde-translation\phpbb-translation\language\de\common.php (7 hits)
>     Line 104:   'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_INCORRECTLY_STORED'    => 'Das OAuth-Token wurde fehlerhaft gespeichert.',
>     Line 171:   'CONFIRM_CODE_WRONG'    => 'Der eingegebene Bestätigungscode ist fehlerhaft.',
>     Line 334:   'IMAGE_FILETYPE_MISMATCH'   => 'Fehlerhafter Grafikdateityp: Dateiendung %1$s erwartet, aber Endung %2$s erhalten.',
>     Line 372:   'LOGIN_CONFIRM_EXPLAIN'             => 'Um einen Brute-Force-Angriff auf Benutzerkonten zu verhindern, musst du nach einer bestimmten Anzahl von fehlerhaften Anmeldungen einen Bestätigungscode angeben. Der Code wird im unten stehenden Bild angezeigt. Wenn du nur über ein eingeschränktes Sehvermögen verfügst oder aus einem anderen Grund den Code nicht lesen kannst, kontaktiere bitte die %sBoard-Administration%s.', // unused
>     Line 376:   'LOGIN_ERROR_PASSWORD'              => 'Du hast ein fehlerhaftes Passwort angegeben. Bitte prüfe dein Passwort und versuche es erneut. Wenn du weiterhin auf Probleme stößt, wende dich bitte an die %sBoard-Administration%s.',
>     Line 378:   'LOGIN_ERROR_USERNAME'              => 'Du hast einen fehlerhaften Benutzernamen angegeben. Bitte prüfe deinen Benutzernamen und versuche es erneut. Wenn du weiterhin auf Probleme stößt, wende dich bitte an die %sBoard-Administration%s.',
>     Line 873:   'WRONG_PASSWORD'    => 'Du hast ein fehlerhaftes Passwort angegeben.',
>   H:\phpbbde-translation\phpbb-translation\language\de\plupload.php (1 hit)
>     Line 58:    'PLUPLOAD_ERR_UPLOAD_URL'   => 'Die hochzuladende URL ist entweder fehlerhaft oder existiert nicht.',
>   H:\phpbbde-translation\phpbb-translation\language\de\ucp.php (1 hit)
>     Line 193:   'CUR_PASSWORD_ERROR'        => 'Das angegebene derzeitige Passwort ist fehlerhaft.',

**Comment by gn36** [comment]
In meinen Augen ist "fehlerhaft" in einigen Fällen eine abgeschwächte Version von "falsch", frei nach dem Motto "Das ist nicht nur fehlerhaft, sondern rundweg falsch." Ich finde auch, "fehlerhaft" klingt oft freundlicher als "falsch": Mit "falsch" unterstellt man dem Anwender oft Unvermögen, mit "fehlerhaft" nur eine kleine Unachtsamkeit.

Ich würde es also am Besten finden, wenn wir Eingaben des aktuellen Users als "fehlerhaft" bezeichnen - sonstige Daten eher als "falsch".

Zum Beispiel so wie das hier auch schon ist:

> Line 452: 'ACP_SERVER_SETTINGS_EXPLAIN' => 'Hier kannst du einige Einstellungen bezüglich Server und Domain vornehmen. Bitte stelle sicher, dass die Daten, die du eingibst, auch wirklich stimmen, denn **fehlerhafte Angaben könnten zu E-Mails führen, die falsche Informationen enthalten**. Wenn du den Domain-Namen eingibst, denk daran, dass http:// oder eine andere Protokoll-Bezeichnung darin enthalten ist. Ändere den Port nur, wenn du weißt, dass dein Server einen anderen Port nutzt; Port 80 ist in den allermeisten Fällen richtig.',

**Comment by Philipp-K** [comment]
Ich bin das jetzt einmal komplett durchgegangen und habe jetzt grundsätzlich auf "fehlerhaft" umgestellt. Ausnahmen:
- Bei Passwörtern, Bestätigungscodes habe ich falsch verwendet, da es sich hier um ein hartes "Falsch" handelt
- Es ist etwas falsch gelaufen, es geht etwas falsch, das ist falsch, ... (als feststehende Formulierung)

Läuft im Wesentlichen darauf hinaus, dass falsch eher für einen inhaltlichen Fehler, fehlerhaft eher für einen syntaktischen Fehler steht (die Uhr geht falsch; sie läuft fehlerhaft). Lässt sich aber nicht immer hundertprozentig zuordnen
