### ISSUE TITLE
Fragwürdige Übersetzung im ACP?

### ISSUE THREAD

**Issue by Elsensee** [phpbb-de/phpbb-translation#149]
1. acp/board.php - Z. 505
   `'FORM_TIME_MAX_EXPLAIN'            => 'Die Zeit, die ein Benutzer hat, um ein Formular abzusenden. Stelle als Wert -1 ein, um das Verhalten abzuschalten. Beachte, dass ein Formular unabhängig dieser Einstellung ungültig werden kann, wenn die Sitzung abläuft.',`
   Sollte es hier nicht besser "unabhängig _von_ dieser Einstellung" lauten?
2. Problem ist der Vorgang beim Deinstallieren einer Erweiterung
   Hier soll man erst die Daten und dann die Dateien löschen. Dies kann man schnell verwechseln - gibt es hier keine bessere Option? (geht hier um die acp/extensions.php)
   Besonders bei einem Update wird dies klar, da einige vielleicht denken könnten, dass der Link "Daten löschen" die Dateien auf dem Server löscht.

**Comment by Philipp-K** [comment]
1. Das "unabhängig" kann man wohl um ein von ergänzen
2. Man müsste es dann wohl etwas umständlich umschreiben. Irgendwas in Richtung "Datenbank-Daten" (was sich bescheiden anhört). Tendiere gerade eher dazu, es zu lassen - gute Vorschläge werden aber angenommen.
3. Zwei getrennte Issues wären praktischer gewesen :-)

**Comment by Philipp-K** [comment]
Hat jemand eine Idee für 2.?

**Comment by Crizz0** [comment]
Datenansammlung?
Datenbank-informationen? 
Datenbank-Einträge?

**Comment by Philipp-K** [comment]
Datenbank-Einträge wäre wohl eine mögliche Alternative

**Comment by nickvergessen** [comment]
Nun es handelt sich nicht zwangsweise nur um Datenbankzeug, deswegen haben wir data genommen und nicht database xyz.

**Comment by Philipp-K** [comment]
Hier mal die entsprechenden Strings:

```
'EXTENSION_REMOVE_HEADLINE' => 'Eine Erweiterung komplett aus dem Board entfernen',
'EXTENSION_REMOVE_EXPLAIN'  => '<ol>
        <li>Deaktiviere die Erweiterung</li>
        <li>Lösche die Daten der Erweiterung</li>
        <li>Lösche die Dateien der Erweiterung aus dem Dateisystem</li>
    </ol>',
```

**Comment by Crizz0** [comment]
Ist denn Daten jetzt = Dateien + Datenbank-Einträge 

Oder nur das eine/andere, oder wie?

**Comment by nickvergessen** [comment]
Also phpBB an sich löscht nur die Daten. Im Normalfall heißt das es macht die Migration-Änderungen rückgängig.
Allerdings könnte ein Ext Autor in den Schritt auch manuell einbauen, dass alles mögliche gemacht wird. Z.B.: alle Avatare gelöscht, die Dateien der Erweiterung gelöscht oder eine andere Extension deaktiviert wird.

**Comment by Philipp-K** [comment]
Wenn wir
- Lösche die von der Erweiterung gespeicherten Daten (kurz ggf. Daten löschen)
- Lösche die Programmdateien der Erweiterung aus dem Dateisystem

nehmen, passt es meiner Ansicht nach.

**Comment by Philipp-K** [comment]
Meinungen?

**Comment by gn36** [comment]
Die Erweiterung an sich ist ja in ihrem eigenen Verzeichnis. Daher würde auch sowas gehen:

> Lösche das Programm-Verzeichnis der Erweiterung aus dem Dateisystem

Alternativ fände ich folgende Liste ganz gut:

```
<li>Deaktiviere die Erweiterung</li>
<li>Lösche die Datenbankinhalte und die Arbeitsdaten der Erweiterung</li>
<li>Lösche die Erweiterung aus dem Dateisystem</li>
```

Ob wir da die Datenbankinhalte nun explizit aufführen oder nicht ist glaube ich egal, aber "Arbeitsdaten" ist denke ich eine klare Abgrenzung gegenüber den Programmdateien.

**Comment by Crizz0** [comment]
Ist brauchbar. Auch wenn "Arbeitsdaten" schon ein wenig ungewöhnlich ist.

**Comment by Philipp-K** [comment]
Wir brauchen allerdings für den zweiten Punkt ("Lösche die Datenbankinhalte und die Arbeitsdaten der Erweiterung") eine Kurzform für die entsprechende Aktion im Admin-Bereich.

**Comment by LehrlingBeate** [comment]
Und wie wär's mit "Lösche die Erweiterung" analog zu "Deaktiviere die Erweiterung"?
Ob es den Nutzer wirklich interessiert, welche Daten da jetzt genau gelöscht werden? 
Zudem erscheint ja zunächst noch einmal diese rot unterlegte Warnung, in der darauf hingewiesen wird, dass alle Daten und Einstellungen dieser Erweiterung entfernt werden, wenn er jetzt auf Daten löschen klickt. An dieser Stelle erhält der Benutzer also die Info, dass alle Daten entfernt werden. Deswegen könnte man darauf in der Kurzform verzichten.
LG Beate

**Comment by Philipp-K** [comment]
Lösche die Erweiterung ist leider nicht eindeutig und daher meiner Ansicht nach missverständlich.

Die Installation hat drei Schritte, die ersten beiden müssen im ACP ausgeführt werden, der dritte manuell. Für die ersten beiden braucht es daher eine verständliche Kurzform, die im ACP angezeigt werden kann.

Beim ersten (Deaktiviere die Erweiterung - Kurzform: Deaktivieren) sind wir uns wohl einig

Beim zweiten wäre mein Vorschlag weiterhin "Lösche die Daten der Erweiterung" mit der Kurzform "Daten löschen". Die Variante "Lösche die Datenbankinhalte und die Arbeitsdaten der Erweiterung" ist zwar konkreter, allerdings finde ich dazu keine passende Kurzform

Beim letzten können wir uns zwischen "Lösche die Erweiterung aus dem Dateisystem" und "Lösche die Dateien der Erweiterung aus dem Dateisystem", wobei ich letzteres bevorzugen würde.

**Comment by gn36** [comment]
Ich habe mir mal angesehen, wie das an anderen Stellen gelöst ist.
Android nennt ähnliche Schritte so:
- Deaktivieren (ist hier aber Alternative zu Deinstallieren, wenn das nicht möglich ist, also z.B. System Apps)
- Daten löschen
- Deinstallieren

Im Grunde muss man alles ausführen, um wirklich die Erweiterung zu deinstallieren, aber meist ist es  das Entfernen der Software, was als Deinstallation bezeichnet wird. Sehr häufig werden ja die Arbeitsdaten nicht entfernt, wenn man deinstalliert, daher würde es in meinen Augen Sinn machen, den letzten Schritt als Deinstallation zu bezeichnen.

Als Kurzvariante für Arbeitsdaten und DB wäre "Arbeitsdaten löschen" brauchbar. Dann kann man gedanklich die DB zu den Arbeitsdaten zählen (und müsste sie dann konsequenterweise in der Langform eigentlich weglassen). Ist für mich auch immer noch besser, als "Daten löschen", weil es klar macht, dass eben nicht die Erweiterung selbst gemeint ist.

**Comment by LehrlingBeate** [comment]
wäre "zugehörige Daten löschen"  als Kurzform für "Lösche die Datenbankinhalte und die Arbeitsdaten der Erweiterung" denkbar?

**Comment by Philipp-K** [comment]
Also dann
1. Deaktiviere die Erweiterung (Deaktivieren)
2. Lösche die Arbeitsdaten der Erweiterung (Arbeitsdaten löschen)
3. Lösche die Dateien der Erweiterung aus dem Dateisystem
?

@gn36 Beim Deinstallieren in Android löscht du gleich die Anwendungsdaten mit. Damit ist deinstallieren alleine zweideutig, so dass ich das gerne vermeiden würde

**Comment by gn36** [comment]
Fände ich ok
