### ISSUE TITLE
Notifications =/ subscriptions => Deutsch: 2x Benachrichtigung

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#155]
Ruf man den Link: ucp.php?i=177 auf, erhält man die Einstiegs-Seite beim UCP.

Dort steht im Englischem in der Leiste:
- Manage subscriptions
- Manage notifications

Und wir haben im Deutschen: 
- 2x Benachrichtigungen verwalten

Siehe: 
![benachrichtigung](https://cloud.githubusercontent.com/assets/1311778/3953006/c7f172c6-26e7-11e4-83bc-2126886acce3.PNG)

Da sollten wir uns eine andere Übersetzung für "Subscriptions" überlegen.

**Comment by gn36** [comment]
Abonnements?

**Comment by Crizz0** [comment]
Finde ich nicht schlecht.

**Comment by Philipp-K** [comment]
Das zieht sich recht böse durch das ganze Forum, da wie bislang für "Subscriptions and Bookmarks"  "Benachrichtigungen und Lesezeichen" verwendet haben. Daher bitte die Änderungen gründlich prüfen (vor allem auf Vollständigkeit)

**Comment by gn36** [comment]
Puh, mir war irgendwie nicht bewusst dass das so eine riesige Änderung gibt, wenn man das alles vereinheitlicht. Kriegen wir mit dem Support Probleme, wenn wir so eine altbekannte Funktion umbenennen? Immerhin heißt das schon seit einigen Jahren "beobachten". Auf lange Sicht ist es aber sicherlich besser wenn es Einheitlich benannt ist. Oder können "Subscriptions" noch andere Dinge sein als nur beobachtete Themen/Foren?

Als Gegenteil von abonnieren würde ich ehrlich gesagt aber "abbestellen" verwenden. Hört sich imho besser an als "nicht mehr abonnieren". "Abonnement beenden" finde ich auch ganz gut, das passt aber nicht immer.

**Comment by Philipp-K** [comment]
Die erste Frage hatte ich mir auch gestellt - aber wir bekommen sonst mehrfach Probleme mit unklaren Bezeichnungen.
Wenn sollten wir aber "Abonnement abbestellen" verwenden, weil bei "abbestellen" allein der Kontext nicht klar ist. Allerdings sieht das irgendwie komisch aus

**Comment by gn36** [comment]
Ich denke das hängt vom Kontext ab - Abonnement beenden ist wie gesagt da wo du es verwendet hast ganz gut, eventuell passt es noch an ein paar mehr Stellen. 

Nachdem ich noch mal einen Blick darauf geworfen habe gebe ich dir recht: "abbestellen" könnte sich auch auf Lesezeichen o.ä. beziehen und Abonnement abbestellen ist auch eher ungünstig.

**Comment by Philipp-K** [comment]
Bin das jetzt nochmals alles durchgegangen und hab noch ein paar Ersetzungen vorgenommen
