### ISSUE TITLE
Klicke auf / Klicken Sie auf...

### ISSUE THREAD

**Issue by Philipp-K** [phpbb-de/phpbb-translation#175]
Insbesondere in den FAQs haben wir ein paar Fomulierungen wie "Wenn Sie ..., klicken Sie auf ..." - hört sich nicht gut an und sollte nach Abschluss der Überarbeitung an den FAQ ausgegriffen werden.

**Comment by Crizz0** [comment]
Nur das, oder? 

Da fällt mir allerdings aktuell nicht so viel ein. :/
