### ISSUE TITLE
Eine statt ein help_faq.php

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#180]
"Um eine neues Thema in einem Forum zu eröffnen"

Da muss in beiden Sprachen de und de_x_sie ein "Um ein neues Thema..." hin.

**Comment by Elsensee** [comment]
Und in der selben Zeile "Um auf einen Beitrag zu antworten" statt "Um auf einen Beitrag zu antworten" ;) ;D
