### ISSUE TITLE
Jumpbox --> "Forum wechseln"

### ISSUE THREAD

**Issue by gn36** [phpbb-de/phpbb-translation#184]
Ich eröffne hierzu mal ein Ticket, vgl. auch https://www.phpbb.de/community/viewtopic.php?f=141&t=231393&start=10#p1328984

Die Jumpbox wird auch in Bereichen angezeigt, die kein Forum sind. In dem Fall ist die Bezeichnung "Forum wechseln" ungünstig, weil man aktuell nicht im Forum ist. Zum Beispiel ist die Jumpbox auf den Profilseiten enthalten.

Lösungsmöglichkeiten:
- Zu Forum wechseln
- Zu Forum springen
- Gehe zu (wie in 3.0)

**Comment by Crizz0** [comment]
Wo ist denn die Jumpbox noch? Außer auf dem Profil?

**Comment by gn36** [comment]
Das Ding ist an ziemlich vielen Stellen einfach unten drunter, Mitgliederliste, Suchergebnisse, FAQ, Teamseite. Mehr habe ich gerade nicht gesehen, aber ich würde sagen, der Begriff muss schon ziemlich allgemein passen.

EDIT: Ich wäre übrigens für Gehe zu. Das ist ähnlich kurz wie im Original und entspricht auch unserer bisherigen Übersetzung in 3.0.

**Comment by Philipp-K** [comment]
IM Englischen haben wir "Jump to" - aber ich meine mich an eine Diskussion zu dem Thema zu erinnern - da ist sie ja: #143

**Comment by gn36** [comment]
Hm, die Diskussion habe ich wohl verpasst.
Ich finde aber, dass "Forum wechseln" nur passen würde, wenn man sich gerade in einem davon befindet - das ist aber bei den anderen Seiten nicht der Fall. 
"Springe zu" aus #143 fände ich auch ok.

**Comment by Philipp-K** [comment]
Vielleicht schaffen wir das noch für 3.1.2

Bei "Springe zu" sehe ich keinen Unterschied zum "Gehe zu" aus 3.0. Ich wäre daher wenn für "Gehe zu" oder "Gehe zu Forum".

Alternativ wäre auch "Zu Forum wechseln" oder "Forum aufrufen" OK. Springen gefällt mir irgendwie nicht.

**Comment by Crizz0** [comment]
1. Gehe zu Forum
2. Zu Forum wechseln

Das wäre so meine TopListe. :+1:
