### ISSUE TITLE
x-Einstellungen im ACP

### ISSUE THREAD

**Issue by Philipp-K** [phpbb-de/phpbb-translation#191]
Siehe https://www.phpbb.de/community/viewtopic.php?f=142&t=232798

Tendiere derzeit dazu, es überall wegzunehmen (außer bei den Board-Einstellungen)

Siehe auch #190

**Comment by gn36** [comment]
Finde ich gut. Das Wort "Einstellungen" bietet bei den meisten Seiten im Adminbereich nur wenig zusätzliche Information - Statistikseiten sind ja recht selten.

**Comment by wintstar** [comment]
Schließe mich dem Kommentar von gn36 an. Bei der Übersetzung in 3.1\* sollte man das responsive Design im Auge behalten. Den einige lange Übersetzungen macht es dann im Smartphone unübersichtlich.

**Comment by Philipp-K** [comment]
Der Bereich mit den Menü-Optionen hat übrigens eine feste Breite - womit auf dem Smartphone genau der gleiche Platz wie auf dem 24-Zöller zur Verfügung steht

**Comment by Crizz0** [comment]
:+1:
