### ISSUE TITLE
USER_CANNOT_DELETE fehlerhaft übersetzt

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#194]
phpBB-3.1.2-deutsch\phpBB3\language\de\posting.php
Original:
'USER_CANNOT_DELETE'        => 'You cannot delete posts in this forum.',

Deutsche Versionen:
'USER_CANNOT_DELETE'        => 'Du darfst deine Beiträge in diesem Forum nicht löschen.',
'USER_CANNOT_DELETE'        => 'Sie dürfen Ihre Beiträge in diesem Forum nicht löschen.',

Erscheint beim Löschen eines fremden Beitrag, den man nicht löschen darf. 

Sollte wohl:
"Du darfst keine Beiträge in diesem Forum löschen." o.ä. heißen.

**Comment by Philipp-K** [comment]
Betrifft meiner Ansicht nach auch USER_CANNOT_EDIT
