### ISSUE TITLE
"CAPTCHA-Modul-Einstellungen" outdated translation for "Spambot Countermeasures"

### ISSUE THREAD

**Issue by Derky** [phpbb-de/phpbb-translation#20]
[Some phpBB versions ago](https://github.com/phpbb/phpbb/commit/7b1d9fbbe25c6ee28fa248c9f20a9d82a1f386d2#diff-5187de38fcb397cabf24803f560e72a8L193) the term **CAPTCHA module settings** was changed to 
**Spambot countermeasures** (see language key `ACP_VC_SETTINGS`) 

This line was not updated in the German translation, so it still says:
 **CAPTCHA-Modul-Einstellungen**

This [has led](https://www.phpbb.com/customise/db/mod/sortables_captcha_plugin/support/installed_correctly_but_not_showing-t_124906-sid_fa2cf269d633d282ea2ac023e93b8074-p_361261#p361261) to problems when a user tries to find the option from an English instruction. 
![mmnbby1a2h](https://cloud.githubusercontent.com/assets/318762/2855392/181f8eea-d15c-11e3-9609-530e8fbe89d5.jpg)

**Comment by Crizz0** [comment]
Is someone working on this? If no, i will. :D

**Comment by Philipp-K** [comment]
Yes - I am

**Comment by Philipp-K** [comment]
Changed for next language pack for phpBB 3.0 (SVN)

**Comment by nickvergessen** [comment]
@Philipp-K 3.0 is in this git aswell, just send a PR based on the branch develop-olympus against develop-olympus
