### ISSUE TITLE
Übersetzungskonflikte zwischen 3.0.x und 3.1.x

### ISSUE THREAD

**Issue by gn36** [phpbb-de/phpbb-translation#211]
Ich habe gerade mal versucht, die neuen Änderungen an Olympus via Merge nach Ascraeus zu übernehmen.

Dabei sind einige Konflikte aufgetreten, die aufgrund von unterschiedlichen Übersetzungen in beiden Versionen entstehen. Idealerweise sollten wir das vereinheitlichen. Dabei gibt's sowohl Übersetzungen, bei denen nur einzelne Worte unterschiedlich sind als auch Übersetzungen mit komplett anderer Struktur obwohl die Bedeutung gleich bleibt. 

Ein Beispiel (common.php):

> 'MODULE_NOT_FIND' => 'Modul %s kann nicht gefunden werden', 
> 'MODULE_FILE_INCORRECT_CLASS' => 'Die Modul-Datei %s enthält nicht die korrekte Klasse [%s]',

vs (3.1):

> 'MODULE_NOT_FIND' => 'Kann Modul %s nicht finden', 
> 'MODULE_FILE_INCORRECT_CLASS' => 'Die Modul-Datei %s beinhaltet nicht die korrekte Klasse [%s]',

Welche von beiden Versionen besser ist, ist damit natürlich nicht gesagt (in diesem Fall finde ich die erste Zeile von Ascraeus besser, aber die zweite von Olympus). Unschön ist das aber schon, insbesondere wenn im Original die Übersetzungsänderung eigentlich aus Olympus stammt.

Wenn wir das jetzt ein mal ins Reine bringen, haben wir zukünftig weniger Arbeit, weil wir jede Übersetzung nur ein mal machen müssen und nicht doppelt in Olympus und Ascraeus. 

Wenn wir dann in Zukunft Konflikte vermeiden wollen sollten wir statt die Änderungen an Ascraeus direkt ins Git Repository zu übernehmen stattdessen erst die Änderungen an Olympus übernehmen, selbst wenn da gerade keine neue Version ansteht, diese Übersetzen und nach Ascraeus mergen. Dann anschließend erst sollten wir die übrigen Änderungen an Ascraeus übernehmen. Auf die Weise gibt's auch keine doppelten Übersetzungen mit unterschiedlichen Ergebnissen mehr.

**Comment by Philipp-K** [comment]
Die beiden Versionen sind meiner Ansicht nach in der Zwischenzeit zu unterschiedlich, als dass eine gemeinsame Pflege Sinn machen würde. Große Änderungen wird es an 3.0.x sowieso nicht mehr geben.

**Comment by gn36** [comment]
Gut, dann lassen wir das bei 3.0 vs. 3.1 sein, aber bei 3.2 sollten wir dann drauf achten dass wir einfach regelmäßig von 3.1 nach 3.2 mergen und Änderungen, die in beiden Versionen falsch sind einfach immer in der älteren Version machen.

**Comment by Philipp-K** [comment]
Sollten wir meiner Ansicht nach auch von der Menge der Unterschiede abhängig machen.

**Comment by gn36** [comment]
Da bei phpBB.com die Unterschiede von 3.1 nach 3.2 gemergt werden (was auch die Sprachdateien beinhaltet) dürften, sofern das dabei bleibt, eigentlich immer alle Änderungen von 3.1 auch auf 3.2 zu übertragen sein. 

Solange wir also die Änderungen an 3.1 zuerst machen, mergen und dann erst die Änderungen an 3.2 sollte die Gesamtmenge der Unterschiede eigentlich egal sein und wir bekommen konsistente Sprachdateien, die in beiden Versionen den selben Inhalt haben, sofern sich die Bedeutung nicht geändert hat. 

Zu Konflikten kommt es ja nur, wenn wir eine Änderung an der selben Sprachvariable in beiden Versionen unabhängig voneinander durchführen.

Das bedeutet dann zwar, dass bei einem Update für 3.2 gleichzeitig auf jeden Fall die aktuelle Zwischenversion der Sprachdateien für 3.1 importiert werden müsste, aber das erspart einem ja dann beim nächsten 3.1 Update wieder Arbeit.

**Comment by Crizz0** [comment]
3.0 wird nicht weiter unterstützt.
