### ISSUE TITLE
Fehler in "install.php" Hinweis auf 3.1-Version 

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#213]
phpBB-3.0.13-PL1-deutsch\phpBB3\language\de\install.php

Line 567:   'UPGRADE_INSTRUCTIONS'          => 'Eine Upgrade auf eine neue Version <strong>%1$s</strong> ist verfügbar. Bitte lese <a href="%2$s" title="%2$s"><strong>die Bekanntmachung zur Veröffentlichung (Release announcement)</strong></a>, um zu erfahren, welche Neuerungen die Version bietet und wie ein Upgrade durchgeführt werden kann.',

Interessanterweise, zeigt das nach dem Release von 3.1.3 immer noch 3.1.2 an.

**Comment by Philipp-K** [comment]
Sicher, dass das ein Problem mit der Übersetzung ist?

**Comment by Crizz0** [comment]
Nein. Die 3.1.2 statt 3.1.3 liegt an .com.

Trotzdem enthält der Satz einen Fehler, der zu uns gehört. "Eine Upgrade"!

**Comment by Philipp-K** [comment]
Können wir das eigentlich schließen?

**Comment by Crizz0** [comment]
Ja.
