### ISSUE TITLE
install.php: DB_UPDATE_NOT_SUPPORTED

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#216]
'DB_UPDATE_NOT_SUPPORTED' => 'Leider unterstützt diese Skript kein Update von phpBB-Versionen vor „%1$s“. Sie haben momentan Version „%2$s“ instlliert. Bitte aktualisieren Sie auf eine frühere Version, bevor Sie dieses Script ausführen. Unterstützung dabei erhalten Sie in den Support-Foren von phpBB.com und phpBB.de.',

"instlliert" --> "installiert"

**Comment by gn36** [comment]
"frühere Version"? Für mich wäre das synonym mit "ältere Version", was keinen Sinn macht. "neuere Version" wäre imho besser.
