### ISSUE TITLE
frühere/ältere Version vs. neuere Version

### ISSUE THREAD

**Issue by gn36** [phpbb-de/phpbb-translation#222]
Da #218 bereits geschlossen ist eröffne ich einfach mal ein neues Ticket für die Diskussion zum Thema frühere/ältere Version vs. neuere Version.

Verlauf:

gn36:

> Hier auch: "frühere Version" ist imho ungünstig, "neuere Version" trifft es besser. Können wir meinetwegen auch separat behandeln.

PhilippK:

> Ist hier irgendwie eine Frage des Bezugspunkts. Wir haben
> A: aktuell verwendete Version (%2)
> B: Version, ab der das Update unterstützt wird (%1)
> C: Version des verwendeten Installationspakets
> D: Aktuelle Version (kann C entsprechen)
> 
> Letztendlich muss der Anwender auf eine Version >= B und < C updaten, wobei blöderweise nicht klar ist, ob es eine solche Version überhaupt gibt. Aus Sicht von A ist das eine neuere Version, aus Sicht von C eine ältere.

gn36:

> Ok, vielleicht bauen wir auch einfach nur ein "zunächst" ein?
> 
> >  Bitte aktualisiere zunächst auf eine frühere Version, ...
> 
> Oder besser
> 
> > Bitte aktualisiere zunächst auf eine ältere Version,
> 
> völlig klar wäre imho
> 
> > Bitte aktualisiere zunächst auf eine ältere Version als %1

Ergänzung:
mein letzter Vorschlag wäre natürlich gegenüber der Englischen Version eine Änderung, mein Favorit, wenn wir nicht eine Änderung der Englischen Version vorschlagen, wäre daher mein zweiter Vorschlag.

**Comment by Philipp-K** [comment]
Noch mal das Original:

> 'We are sorry, but this script does not support updating from versions of phpBB prior to “%1$s”. The version you currently have installed is “%2$s”. Please update to a previous version before running this script. Assistance with this is available in the Support Forum on phpBB.com.',

**Comment by Philipp-K** [comment]
Etwas freier:

> Dieses Skript unterstützt kein Update von phpBB-Versionen vor „%1$s“. Sie haben derzeit Version „%2$s“ installiert, so dass leider kein direktes Update möglich ist. Sie müssen daher zunächst auf eine frühere Version aktualisieren, die ein Update von Version „%2$s“ unterstützt, bevor Sie dieses Script ausführen können. Unterstützung dazu erhalten Sie in den Support-Foren von phpBB.com und phpBB.de.

**Comment by gn36** [comment]
Der Vorschlag gefällt mir ganz gut. Ob er auch dem Validator gefällt, wenn 2x %2$s darin vorkommt?

**Comment by Crizz0** [comment]
Also laut nickvergessen und Marc sollte diese Variante mit 2x %2$s sowohl beim Test-Script als auch beim Translation-Manager keine Probleme verursachen. Daher würde ich das so machen.

**Comment by nickvergessen** [comment]
Wenn der Validator meckert braucht er n Update.
Aber ich hab das glaub ich damals extra berücksichtigt:
https://github.com/phpbb/phpbb-translation-validator/blob/master/src/Phpbb/TranslationValidator/Validator/LangKeyValidator.php#L533-L559

**Comment by nickvergessen** [comment]
Hab tests hinzugefügt:
https://github.com/phpbb/phpbb-translation-validator/commit/03f202f64e4d766a3a26371141337e228ae0a08c
Und es geht
