### ISSUE TITLE
Sehr umständliche Formulierung bei Verwarnungen

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#242]
In der: \language\de\mcp.php
gibt es u.a. diese Perle.

> Dies ist eine Verwarnung wegen dieses von dir erstellten Beitrags: URL zum Beitrag

Dieser Satz steht in der PN, die dem Verwarnten zu geschickt wird. Das liest sich mMn echt umständlich. Sollten wir mal ausbessern. Auch wenn das Original kaum besser ist:

> 'WARNING_POST_DEFAULT'    => 'This is a warning regarding the following post made by you: %s .',

Ebenso wie:

> 'WARNING_PM_SUBJECT'  => 'Verwarnung erteilt.',
> Da ist mMn "erhalten" oder "Du bist verwarnt worden" besser.

Wobei wir da ein wenig das Original im Auge behalten sollten:

> 'WARNING_PM_SUBJECT'  => 'Board warning issued',

**Comment by gn36** [comment]
Was hältst du von 

> 'WARNING_POST_DEFAULT' => 'Dies ist eine Verwarnung. Sie wurde aufgrund deines folgenden Beitrags erteilt: %s'

Enthält imho die gleichen Infos, ist aber etwas einfacher.

deinen 2. Vorschlag für die PN finde ich gut, egal ob das im Original so klingt, als wäre irgendwer (aber nicht man selber) verwarnt worden.

**Comment by Philipp-K** [comment]
Wie wäre es ganz schlicht mit

> 'WARNING_POST_DEFAULT'    => 'Diese Verwarnung wurde dir wegen folgendem Beitrag erteilt: %s.',

?

Bei WARNING_PM_SUBJECT handelt es sich um die Betreffzeile der Mail an den Benutzer. Die würde ich gerne geschlechtsneutral halten. Ggf. "Es wurde eine Verwarnung erteilt"

BTW: ACL_M_WARN in permissions_phpbb.php sollte dann wohl auch "Kann Verwarnungen erteilen" statt "... aussprechen" heißen.

**Comment by Crizz0** [comment]
Ein

> Du hast wegen folgendem Beitrag eine Verwarnung erhalten: 

Kommt nicht infrage, weil zu weit weg vom Original? 

@ACL_M_WARN: Das würde ich dann wirklich mitmachen.

**Comment by gn36** [comment]
Finde ich auf jeden Fall besser.

**Comment by Crizz0** [comment]
@Philipp-K  "WARNING_PM_SUBJECT" da willst du keine "Du..." oder "Sie.." drin haben?

**Comment by Philipp-K** [comment]
@Crizz0 ja

**Comment by Crizz0** [comment]
Vorschlag: 

> 'WARNING_PM_SUBJECT' => 'Verwarnung erhalten.',

Evtl. mit "Neue Verwarnung erhalten"

**Comment by Philipp-K** [comment]
Würde passen

**Comment by Crizz0** [comment]
Dann noch:

> 'WARNING_POST_DEFAULT'    => 'Du hast wegen folgendem Beitrag eine Verwarnung erhalten: %s.', 

oder

> 'WARNING_POST_DEFAULT'    => 'Diese Verwarnung wurde dir wegen folgendem Beitrag erteilt: %s.',

**Comment by Philipp-K** [comment]
Zu WARNING_POST_DEFAULT: das ist die Vorlage, die bei Erstellung einer Verwarnung verwendet wird. Da muss meiner Ansicht nach ganz klar die Nachricht "Du hast eine Verwarnung erhalten" im Vordergrund stehen. Ich hirne noch...

![warning](https://cloud.githubusercontent.com/assets/845541/9502820/c4cf11c6-4c33-11e5-825d-929d1d366a3c.jpg)

**Comment by Philipp-K** [comment]
![warning2](https://cloud.githubusercontent.com/assets/845541/9502920/48158d76-4c34-11e5-9cdc-3de86220b21a.jpg)

**Comment by Philipp-K** [comment]
Ich wäre für

> Diese Verwarnung wurde dir wegen folgendem Beitrag erteilt: %s.

**Comment by Crizz0** [comment]
Finde ich okay. Würde ich so umsetzen.
