### ISSUE TITLE
Benutzernamen sperren im ACP

### ISSUE THREAD

**Issue by Elsensee** [phpbb-de/phpbb-translation#243]
Im ACP gibt es bei "Benutzer und Gruppen" den Punkt "Benutzernamen sperren", der etwas irreführend wirken kann.
Man könnte vermuten, dass man hier Benutzernamen an sich sperren kann (wobei man dies allerdings beim Punkt "Benutzernamen verbieten" dadrunter macht), obwohl hier Benutzer _nach_ ihrem Benutzernamen gesperrt werden.
Etwas unglücklich wie ich finde.. :/

**Comment by gn36** [comment]
Bessere Lösung: "Benutzer sperren". Das ist imho eindeutig.

**Comment by Elsensee** [comment]
Joa, ich glaub es heißt im Original auch "Ban users".

**Comment by gn36** [comment]
Ich habe gerade in den Sprachdateien gesucht. Ich finde nur acp/users.php: 

> 'USER_ADMIN_BAN_USER'         => 'Über Benutzernamen sperren',

Sowie mcp.php:

> 'MCP_BAN_USERNAMES'           => 'Benutzernamen sperren',

Ersteres macht so imho Sinn. Zweiteres heißt im Original auch "Ban usernames" und ist die Kurzform für das MCP, wo auch für die übrigen Einträge "Ban IP" und "Ban Email" steht. Das können wir ggf. in "Benutzer sperren" ändern.

Im ACP steht zumindest bei 3.1.x "Benutzer sperren", bei 3.0.x habe ich jetzt nicht nachgesehen.

**Comment by Philipp-K** [comment]
Im Original heißt es "Ban Usernames", verwendet wird es im Moderationsbereich im Register sperren:
![banuser](https://cloud.githubusercontent.com/assets/845541/9477433/888757bc-4b72-11e5-86fd-12e39e27f9a1.jpg)

Inhaltlich sperrt man Benutzer anhand des Benutzernamnes

**Comment by gn36** [comment]
Aus dem Grund halte ich "Benutzer sperren" für besser. Bei der Sperrung von IPs können betroffene User sich von anderen IPs ja dennoch anmelden und die Mailadressensperrung sorgt dafür, dass mit selbigen keine Accounts erstellt werden können aber auch wiederum nicht für eine Sperre schon existierender Accounts.

**Comment by Crizz0** [comment]
Dann bin ich dafür, das wir das so ändern. Das verstehen die Leute dann besser.
