### ISSUE TITLE
Bild-Einstellungen ungenau und missverständlich übersetzt

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#248]
Hi,

wir nutzen in den Bild-Einstellungen (ACP > Dateianhänge > Abschnitt: Bildkategorie-Einstellungen) aktuell ein paar missverständliche Übersetzungen:
Deutsch:
![deutsch-bildeinstellungen](https://cloud.githubusercontent.com/assets/1311778/9561671/e530c2d4-4e4f-11e5-8662-f0d56948e1e5.png)
Englisch:
![englisch-bildeinstellungen](https://cloud.githubusercontent.com/assets/1311778/9561672/e9027d76-4e4f-11e5-8103-ea2ee7626c05.png)
1. Punkt: "Maximum thumbnail width in pixel" --> spricht von Größe, das sollte vielleicht eher auch Breite heißen.
2. Punkt: "Maximum image dimensions" --> ebenfalls Bildgröße, sollte evtl. Abmessungen o.ä. sein
3. Punkt: "Image link dimensions" --> "Dateigröße" ist nun wirklich falsch. Da es hier um die Abmessungen geht.

Grüße 

PS: Noch in 3.1.6 bringen?

**Comment by gn36** [comment]
Also:
1. Maximale Breite der Vorschaubilder in Pixeln (da ist zusätzlich noch ein Tippfehler drin)
2. Maximale Bildabmessungen
3. Abmessungen für verlinkte Bilder (gefällt mir genau wie das original nicht besonders, aber alles was genauer ist wird ziemlich lang)

**Comment by Crizz0** [comment]
verlinkte Bilder? Das betrifft aber gar nicht [img]-Bilder.

Wie wärs mit "Abmessungen für als Link eingebundene Dateianhänge"?

**Comment by gn36** [comment]
Da wäre mir auch nicht klar, was das nun heißt.

Hm, vielleicht doch einfach ausführlicher:

> Abmessungen, ab denen angehängte Bilder verlinkt werden

Wobei mir nicht ganz klar ist wie die Funktion arbeitet - ich dachte dafür gibt's Vorschaubilder?

**Comment by Crizz0** [comment]
Wenn die Bilder größer sind als die Abmessungen dort, wird nur ein Text-Link angezeigt und kein Bild.

**Comment by gn36** [comment]
Ok dann würde der Vorschlag ja passen.

**Comment by Crizz0** [comment]
Bezieht sich halt nur auf Dateianhänge, afaik.

**Comment by gn36** [comment]
Bei deinem Vorschlag ist mir aber aus der Überschrift nicht klar, wie die Einstellung arbeitet, ich finde aus "angehängte Bilder" wird auch klar, dass es um einen Dateianhang geht.

Meinetwegen auch 

> Abmessungen, ab denen als Datei angehängte Bilder verlinkt werden

**Comment by Crizz0** [comment]
Ja, finde ich schöner. Würde aber beide Vorschläge okay sind. Letzterer ist halt ziemlich lang.

**Comment by Philipp-K** [comment]
Wenn ihr noch etwas Zeit für die QS lasst, wäre das hilfreich

**Comment by Crizz0** [comment]
Martin ist eben Lucky Luke^^

**Comment by Philipp-K** [comment]
1 passt (mit der Anpassung in #249)

**Comment by Philipp-K** [comment]
2: "Bildabmessungen" finde ich etwas sperring und ungewohnt. Maximale Abmessung von Bildern hört sich für mich besser an. In der Beschreibung dann "Maximale Abmessung von hochgeladenen Bildern"

3: würde ich dann analog machen:
Abmessung, ab der hochgeladene Bilder verlinkt werden (Abmessung im Singular!)
Beschreibung: Hochgeladene Bilder werden als Link dargestellt, wenn deren Abmessung diese Werte überschreitet.

**Comment by gn36** [comment]
Abmessung im Singular bei 3. finde ich ehrlich gesagt an der Stelle dann seltsam, denn hier geht es ja nicht nur um die Breite sondern um Breite und Höhe.
Bei 2 genauso.
