### ISSUE TITLE
Gemischte Verbesserungen aus phpBB.de Diskussionen

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#250]
language/de/acp/groups.php: https://www.phpbb.de/community/viewtopic.php?f=142&t=234644

> 'LEGEND_SORT_GROUPNAME'           => 'Legende bei Name der Gruppe sortieren',

Forums- vs. Forenregeln: https://www.phpbb.de/community/viewtopic.php?f=142&t=233608
language\de\common.php:

> 'FORUM_RULES'         => 'Forumsregeln',
> 'FORUM_RULES_LINK'      => 'Die Forumsregeln lesen',

language\de\acp\forums.php

> 'FORUM_RULES_EXPLAIN'             => 'Die Forumsregeln werden auf allen Seiten innerhalb des jeweiligen Forums angezeigt.',
>     'FORUM_RULES_LINK'                  => 'Link zu den Forumsregeln',
>     'FORUM_RULES_LINK_EXPLAIN'          => 'Du kannst hier die URL einer Seite oder eines Beitrags angeben, die/der deine Forumsregeln enthält. Diese Einstellung wird den eingegebenen Text der Forumsregeln überschreiben.',
>     'FORUM_RULES_PREVIEW'               => 'Vorschau der Forumsregeln',
>     'FORUM_RULES_TOO_LONG'              => 'Die Forumsregeln sind zu lang. Sie müssen weniger als 4000 Zeichen umfassen.',
>     '

**Comment by Crizz0** [comment]
Also das 1. sollte mMn untrittig sein. Ein:

> Legende nach Gruppennamen sortieren

klingt viel besser.

Beim zweiten sollten wir es definitiv einheitlich machen und ich finde, Forenregeln, klingt einfach schöner. Wobei ich jetzt wirklich nicht weiß, ob es eine "falsche" Version gemäß Rechtschreibung gibt.

**Comment by Philipp-K** [comment]
1 passt.

Bei 2 muss ich mal im Archiv suchen...

**Comment by Philipp-K** [comment]
zu 2) Wir haben uns damals mit folgendem Argument für Forumsregeln entschieden:

> Bei "Forenregeln" bleibt zu beachten das es sich jeweils um die Regeln eines Forums handelt, "Forumsregeln" ist also grammtikalisch korrekt.

Imho zieht das Argument weiterhin. Es sind die Regeln für **ein** Forum, die Forenregeln wären für alle Foren.

**Comment by Crizz0** [comment]
Das ist schon logisch. Klingt aber in meinen Ohren trotzdem nicht gut.

**Comment by Philipp-K** [comment]
Vielleicht "Regeln des Forums" statt "Forumsregeln"

**Comment by Crizz0** [comment]
Da ist mir letzteres noch lieber. Das ist immerhin kompakter und damit einfacher zu lesen. 

Trotzdem finde ich den Begriff echt panne. :-1:

**Comment by mungo** [comment]
Ich bin für "Forumsregeln". "Forenregeln" ist als Übersetzung einfach falsch.

**Comment by Crizz0** [comment]
Wenn uns nix besseres einfällt. Dann kann der PR #252 so auch gemerged werden.
