### ISSUE TITLE
Tests auf 3.2.0-a1 aktualisieren 

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#257]
Es gibt ein neues Validation-Tool in Version 1.3.9 mit phpBB 3.2.0 Support: https://www.phpbb.com/community/viewtopic.php?f=79&t=2205631#p13425776

Das muss hier noch integriert werden. 

@gn36 Ich hab es runtergeladen und entpackt in einen neuen branch. "vendor" ist allerdings in "gitignore" markiert, wonach er nix pushen würde. Hast du das damals anders ergänzt oder muss man temporär das gitignore anpassen?

**Comment by gn36** [comment]
Ich habe auf das Forum leider keinen Zugriff bei .com Kannst du mir einen direkten Link zu dem Tool schicken (oder den Post ggf. auf phpbb.de zitieren), so dass ich mal einen Blick drauf werfen kann? Oder ist das einfach nur ein anderer Branch im bisherigen Validierungstool? 

So oder so: Vendor hat im Repository normalerweise nichts verloren. Für die Validierung sind in der .travis.yml Anweisungen enthalten, so dass die von Travis selbst heruntergeladen werden (in diesem Fall einfach die Zeile
<code> - php composer.phar install --dev --no-interaction --prefer-source</code>

Ich vermute also dass wir einfach nur die composer.json im Branch 3.2.x anpassen müssen, es sei denn, es soll auch 3.1.x mit der neuen Version getestet werden.

**Comment by Crizz0** [comment]
https://www.phpbb.de/community/viewtopic.php?p=1346688#p1346688

Ich habs dir mal hochgeladen.
