### ISSUE TITLE
Wenn diese Option gesetzt ist / aktiviert ist

### ISSUE THREAD

**Issue by Philipp-K** [phpbb-de/phpbb-translation#26]
Wird derzeit beides verwendet und sollte vereinheitlicht werden
I.d.R. "If this Option is enabled"

**Comment by nickvergessen** [comment]
Ich wär für aktiviert

**Comment by Philipp-K** [comment]
Ich möchte da auf jeden Fall nochmals alle Varianten sichten, auch wenn sich "aktiviert" meiner Ansicht nach besser anhört. Die Frage ist halt, ob es immer passt.
Wir haben da ja immer eine Beziehung zwischen Bedingung und Wirkung. Wenn das Kontrollkästchen gesetzt ist, passiert irgendwas. "Gesetzt" kann sich meiner Ansicht nach nur auf die Bedingung beziehen, "aktiviert" hingegen auf Bedingung und Wirkung. Könnte also unter Umständen problematisch werden. Frei erfundenes Beispiel: "Wenn diese Option gesetzt ist, ist das Board deaktiviert" - ist wohl besser als "Wenn diese Option aktiviert ist, ist das Board deaktiviert".
