### ISSUE TITLE
Vereinheitlichung Service/Dienst

### ISSUE THREAD

**Issue by Philipp-K** [phpbb-de/phpbb-translation#266]
Nachdem da in der board.php auch noch ein kleiner Typo drin ist, würde ich das nachgelagert machen. Wäre auch ein Kandidat, das gleich sauber von der 3.1 aus zu machen...

**Comment by Philipp-K** [comment]
Ach ja: ich würde einheitlich "Dienst" verwenden

**Comment by Philipp-K** [comment]
Zwei Milestones gehen wohl nicht :-?

**Comment by Crizz0** [comment]
#264 Ist auch nach 3.2.x übernommen worden: https://github.com/phpbb-de/phpbb-translation/commit/5d8d6f752b074a49315516b67c0aa902efc0e625

**Comment by Crizz0** [comment]
#273

**Comment by Philipp-K** [comment]
Muss noch auf 3.2 transformiert werden (und ich scheitere gerade daran)

**Comment by Crizz0** [comment]
Das mach ich nach dem Release von 3.1.7 Paket dann einfach.

**Comment by Philipp-K** [comment]
a) gibt's ja evtl. weitere Stellen und
b) muss ich das auch irgendwie hinbekommen

**Comment by Crizz0** [comment]
Ist auf 3.2 übertragen.
