### ISSUE TITLE
JUMP_TO != Gehe zu Forum

### ISSUE THREAD

**Issue by gn36** [phpbb-de/phpbb-translation#271]
Siehe auch https://www.phpbb.de/community/viewtopic.php?f=141&t=231393&start=20#p1346386

JUMP_TO in der common.php sollte mit "Gehe zu", wie in phpBB 3.0 übersetzt werden statt "Gehe zu Forum"

Die Bezeichnung mit Forum passt nicht, da Erweiterungen auch Einträge für andere Seiten in die Jumpbox eintragen können und diese dann anzeigen. Auf Englisch passt die Bezeichung in dem Fall trotzdem, bei uns leider nicht.

Wir haben da schon mal eine Änderung durchgeführt, vgl. #184 und #143.

Ich bin auch weiterhin für "Gehe zu".

**Comment by Philipp-K** [comment]
Ich kann bei mir gerade keine Begeisterung finden, die Übersetzung zum dritten Mal für 3.1.0 anzupassen...
Ich sehe da auch die Autoren der Erweiterung in der Verantwortung. Wird eine Sprachvariable in einem anderen Kontext verwendet, so kann es auch sein, dass sie nicht mehr passt.

**Comment by gn36** [comment]
Das stimmt natürlich. Aber die Sprachvariable wird da bei Verwendung des Standard Jumpbox Templates nicht von den Extension Autoren eingesetzt, sondern von phpBB selbst:

```
<!-- IF S_IN_MCP and S_MERGE_SELECT -->{L_SELECT_TOPICS_FROM}<!-- ELSEIF S_IN_MCP -->{L_MODERATE_FORUM}<!-- ELSE -->{L_JUMP_TO}<!-- ENDIF -->
```

phpBB selbst ändert hier also die Sprachvariable, abhängig vom Kontext in dem die Jumpbox verwendet wird, aber es ist keine Möglichkeit vorgesehen, hier eine eigene Bezeichnung einzubringen.

Wenn die Extension Autoren das Template hier nicht mitnutzen, müssen sie ein eigenes beilegen oder die Sprachvariable überschreiben, denn ein Event ist an der Stelle nicht vorgesehen. 

Sprachvariablen die sich explizit auf Themen oder Foren beziehen haben meist eine entsprechende Bezeichnung drin, das ist hier aber nicht der Fall. Natürlich kann es sein, dass eine Übersetzung nicht in allen Sprachen so allgemein möglich wäre, aber in meinen Augen ist sie das hier eigentlich schon. Wenn die Übersetzung einer Sprachvariable namens "JUMP_TO_FORUM" in falschem Kontext verwendet würde, dann würde ich das genauso sehen wie du, aber nicht bei "JUMP_TO". Ich halte unseren Kontext hier für falsch, JUMP_TO ist in meinen Augen ähnlich generisch wie "YES" oder "NO".

**Comment by Crizz0** [comment]
Aber das JUMP_TO wird doch nur genau in EINEM Kontext verwendet, ergo wenn ein Forum angesprungen werden soll. Oder nicht?

**Comment by gn36** [comment]
Ohne Extensions schon. Mit Extensions kann man anscheinend auch woanders hin springen. Das geht dann auf Englisch, aber nicht auf Deutsch.

**Comment by Crizz0** [comment]
Mal am Beispiel der Dutch-Übersetzung

> 'JUMP_TO'             => 'Ga naar',

oder Französisch:

> 'JUMP_TO'             => 'Atteindre',

Wäre jetzt zweimal ohne Zusatz von "Forum" und damit kompatibel. 

Von daher würde ich unser Jump_to wieder ändern, wenn nichts wichtiges dagegen spricht. Damit die Mehrfachnutzung auch bei uns möglich ist. Damals kam das "Gehe zu Forum" in die Übersetzung, weil es damals in Area51 diskutiert wurde, auch ein "Jump to Forum" zu nutzen. Da hat man sich allerdings dagegen entschieden. Somit dichten wir jetzt doch ein wenig dazu.

**Comment by mungo** [comment]
Unsere Änderung war damals meiner Meinung nach etwas unglücklich und kann auch nicht ganz nachvollziehen, warum es geändert wurde. Für die englischen Dateien wurde es zwar diskutiert, aber nicht umgesetzt. 
Aktuell verwenden die Autoren die Sprachvariable meiner Meinung nach auch nicht in einem anderen Kontext. Das ist ein Navigationselement und es steht nirgendwo dabei, dass es nur für die Navigation zwischen den Foren gedacht ist.
Ich finde sowohl "Gehe zu" als auch "Springe zu" völlig ausreichend und auch passend. Von daher wäre ich dafür es wieder zu ändern.

**Comment by Crizz0** [comment]
@Elsensee @Philipp-K noch ne Meinung?

**Comment by Philipp-K** [comment]
Irgendwie werde ich damit noch nicht glücklich - was aber wohl mehr am "Gehe zu" als am "Forum" liegt. Das ist ja immer im Kontext "Gehe zu 'Name des Forums'" - was aber meinem Gefühl nach kein wirklich sauberer Sprachgebrauch im Deutschen ist. Eher in Richtung "Wechsle zu" oder so was.

**Comment by Crizz0** [comment]
Ich finde das gibt dich beides nichts:
- Gehe zu
- Wechsle zu

Deshalb bin ich eher für die kürzere Version.

**Comment by mungo** [comment]
Das mit dem Sprachgebrauch kann ich nicht nachvollziehen. "Gehe zu" bevorzuge ich auch gegenüber "Wechsle zu" und nicht wegen der Länge.
Mit der aktuellen Übersetzung gibt es auch bspw. so Konstrukte wie "Gehe zu Forum Support-Forum". Finde ich auch nicht wirklich schön.

**Comment by gn36** [comment]
Ich sehe das wie Mungo und Crizzo

**Comment by Crizz0** [comment]
3.1.7-PL1 ist erschienen. Ich würde das hier daher gerne noch mit reinbringen. @Philipp-K Wie sieht es aus? Trägst du die Meinung mit oder hast du noch einen alternativen Vorschlag?

**Comment by Philipp-K** [comment]
Mangels besserer Alternative machen wir's so

**Comment by Crizz0** [comment]
Für phpBB 3.2 noch relevant.

**Comment by Crizz0** [comment]
Closed via https://github.com/phpbb-de/phpbb-translation/commit/67a9766c00244dd36775150ed684da7ea519dbb3
