### ISSUE TITLE
Modifkation > Erweiterung (Wort ersetzen)

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#272]
Wie in language/de/install.php 'SUPPORT_BODY'
- [x] Änderung in 3.1 vorgenommen
- [x] Änderung nach 3.2 übertragen
- [x] Weitere Vorkommnisse in 3.2 ersetzt.

**Comment by Crizz0** [comment]
Ich kann dafür in 3.1.x nichts mehr finden, habt ihr noch was @Philipp-K und @gn36 ?

**Comment by gn36** [comment]
Dito, ich habe in 3.1 den Begriff "Modifikation" nicht finden können. Das einzige was ich gefunden habe war "QUICK_MOD" und das bezieht sich ja auf Moderation und wird auch korrekt übersetzt.

**Comment by Crizz0** [comment]
Gut, dann sollte das jetzt passen.
