### ISSUE TITLE
Go-Verweise von 3.1 auf 3.2 ändern und auf dem Server einpflegen

### ISSUE THREAD

**Issue by Philipp-K** [phpbb-de/phpbb-translation#275]

**Comment by Crizz0** [comment]
Aktuell vorhandene Go-Verweise in phpBB 3.2:

> /go/3.2/styles  --> https://www.phpbb.de/community/viewforum.php?f=152
> /go/3.2/ersteschritte --> https://www.phpbb.de/infos/tour.php
> /go/3.2/support --> https://www.phpbb.de/support/ 
> /go/3.2/supportforum --> https://www.phpbb.de/community/viewforum.php?f=145
> /go/3.2/schnellstart --> https://www.phpbb.de/support/doku/3.2/quickstart.php
> /go/3.2/extensions --> https://www.phpbb.de/community/viewforum.php?f=148
> /go/3.2/konvertierung --> https://www.phpbb.de/kb/convert_others 
> /go/3.2/berechtigungen --> https://www.phpbb.de/kb/rechtesystem
> /go/3.2/downloads --> https://www.phpbb.de/downloads/
> /go/3.2/dokumentation --> https://www.phpbb.de/support/doku/3.2/manual.php
> /go/3.2/sprachdateienfehler --> https://www.phpbb.de/community/viewtopic.php?f=141&t=238506

**Comment by Crizz0** [comment]
@mungo Ziele sind oben eingepflegt.

**Comment by mungo** [comment]
Sind aktiviert.

**Comment by Crizz0** [comment]
Danke :)
