### ISSUE TITLE
Übersetzung für phpBB 3.1.8

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#282]
https://gist.github.com/nickvergessen/441447e670547275e6bd 

Die Sache mit der Liste haben wir gerade in der a2 oder b1 vor der Brust.

**Comment by Philipp-K** [comment]
Dann sollten wir erst die 3.2.0 angehen.

**Comment by Crizz0** [comment]
Sehe ich nicht so. Es ist für beta-1 ebenfalls notwendig. Wenn wir es in 3.1.8 übersetzen, können wir es für die Beta 1 übernehmen und umgekehrt. Da 3.1.8 eher eilt, bin ich für dieses zuerst.

**Comment by gn36** [comment]
Übernehmen von 3.1.8 nach 3.2.0 ist einfacher als umgekehrt (merge und fertig, in der anderen Richtung geht das so einfach nicht), daher halte ich die Übersetzung von 3.1.8 ebenfalls für sinnvoller.
