### ISSUE TITLE
 .. / language / de / acp / profile.php 

### ISSUE THREAD

**Issue by Talk19Zehn** [phpbb-de/phpbb-translation#289]
Line 119 find
`'INVALID_CHARS_FIELD_IDENT' => 'Der Feld-Kennung darf nur aus Kleinbuchstaben von a bis z und _ bestehen.',`

replace 
`'INVALID_CHARS_FIELD_IDENT' => 'Die Feld-Kennung darf nur aus Kleinbuchstaben von a bis z und _ bestehen.',`

**Comment by Crizz0** [comment]
Für welche Version gilt das?

**Comment by gn36** [comment]
3.1.x auf jeden Fall schon mal, 3.2. erschlagen wir ggf. per merge.
