### ISSUE TITLE
... / language / de_x_sie / acp / profile.php 

### ISSUE THREAD

**Issue by Talk19Zehn** [phpbb-de/phpbb-translation#290]
Line 119 find
 'INVALID_CHARS_FIELD_IDENT' => 'Der Feld-Kennung darf nur aus Kleinbuchstaben von a bis z und _ bestehen.', 

replace 
 'INVALID_CHARS_FIELD_IDENT' => 'Die Feld-Kennung darf nur aus Kleinbuchstaben von a bis z und _ bestehen.',

**Comment by Crizz0** [comment]
Dopplung.
