### ISSUE TITLE
Language changes for 3.2.0-b2 to 3.2.0-RC1

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#297]
https://gist.github.com/marc1706/c02a908fc2517dbd37c59aba85086e44

**Comment by gn36** [comment]
Die FAQ fliegen komplett raus??

**Comment by Crizz0** [comment]
Ja, die alte FAQ, die neue FAQ haben wir ja mittlerweile in help/ ausgelagert: https://github.com/phpbb-de/phpbb-translation/tree/3.2.x/language/de/help Quasi 1:1. Die alte Datei wurde aber jetzt erst gelöscht, dass war für die Diffs besser.

Grüße
