### ISSUE TITLE
Übersetzung VigLink

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#314]
`Solange noch nicht klar ist wo das hin muss habe ich die viglink Übersetzung erst mal in meinem Github Clone abgelegt: https://github.com/gn36/phpbb-ext-viglink/tree/translation/de

Könnt ihr vielleicht auch schon mal ansehen. Nur de, noch nicht de_x_sie`

Sobald klar ist, wie es umgesetzt wird, kommen die Sprachdateien evtl. noch ins Paket.

**Comment by Philipp-K** [comment]
Hab mal 'ne Ladung Kommentare hinterlassen

**Comment by Crizz0** [comment]
Und wohin hast du die Kommentare geschrieben?

**Comment by Philipp-K** [comment]
Eigentlich nach https://github.com/gn36/phpbb-ext-viglink/blob/translation/de/language/de/viglink_module_acp.php - nur da finde ich die nicht mehr :-?

**Comment by gn36** [comment]
Sie hängen an einem commit dran https://github.com/gn36/phpbb-ext-viglink/commit/4e7b1c3b8b70bcd1862006995cd518096791ceec#commitcomment-20306936
Ich habe zwei Mails bekommen. Werde ich sie Tage einarbeiten. In welcher Form reichen wir das denn jetzt eigentlich ein?

**Comment by Crizz0** [comment]
Mit ins Komplettpaket ist momentan am wahrscheinlichsten. Mach mal einen PR mit ext/phpbb/viglink/language/de ...

**Comment by gn36** [comment]
Hm, kriegen wir das vernünftig in die Lang Pack Checks integriert? Die Komplettpaket Skripte müssen wir wohl auch überarbeiten vermute ich mal. Ich werde mal einen PR erstellen, der sowohl de als auch en enthält.

Ich habe Philipps Anmerkungen mal eingearbeitet und auch schon mal die "Sie" Version erstellt. Verlinke ich jetzt nicht neu, kommt ja dann im PR.

**Comment by Philipp-K** [comment]
Ist ja erledigt

**Comment by gn36** [comment]
Hm, hätte es eigentlich automatisch schließen sollen, dafür hatte ich doch ein "fixes xy" eingetragen.
