### ISSUE TITLE
Changes for 3.2.0 stable

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#319]
RC2 zu 3.2.0: https://gist.github.com/marc1706/6bcca41065117b5438b85ca216e600e1

**Comment by Philipp-K** [comment]
Bevor wir es doppelt machen: ich würde das die nächste Stunde machen - oder bist du schon dran?

**Comment by Crizz0** [comment]
Kannst loslegen, habe nicht angefangen

**Comment by Philipp-K** [comment]
EXTENSION_NOT_INSTALLED war schon angepasst
