### ISSUE TITLE
Klärung der offenen Plural-Warnungen

### ISSUE THREAD

**Issue by Philipp-K** [phpbb-de/phpbb-translation#321]
Aus #317 

> Warning in language/de/acp/search.php:SEARCH_INDEX_CREATE_REDIRECT:
Warning in language/de/acp/search.php:SEARCH_INDEX_CREATE_REDIRECT_RATE:
Warning in language/de/acp/search.php:SEARCH_INDEX_DELETE_REDIRECT:
Warning in language/de/common.php:NOTIFICATION_X_OTHERS:
Warning in language/de/common.php:TOTAL_POSTS_COUNT:
Warning in language/de/common.php:TOTAL_TOPICS:
Warning in language/de/common.php:TOTAL_USERS:
Warning in language/de/posting.php:TOO_MANY_CHARS_LIMIT:

Da sollten wir für 3.2.1 klären, ob wir das ändern wollen.

**Comment by Crizz0** [comment]
Nehmen wir das mit? @Philipp-K @gn36 Oder für 3.2.2?

**Comment by gn36** [comment]
Ich schaffe das gerade zeitlich nicht. Wenn du es machen willst dann gerne. Wirklich relevant sind aber ja nur eher pathologische Fälle, von daher können wir es wohl auch schieben.

**Comment by Philipp-K** [comment]
Schieben

**Comment by Crizz0** [comment]
Also ich weiß nicht, was wir da ergänzen wollen. Z.B. posting.php:
```
	'TOO_MANY_CHARS_LIMIT'		=> array(
		2	=> 'Es sind maximal %1$d Zeichen erlaubt.',
	),
```
da können wir ja schlecht einen weiteren Fall "Es ist maximal 1 Zeichen erlaubt" einführen, was gibt denn das für einen Sinn?

**Comment by Crizz0** [comment]
@Philipp-K @gn36 ?

**Comment by gn36** [comment]
Ich habe ja schon geschrieben, dass es eher um pathologische Fälle geht. Wenn du irgend ein Feld auf genau ein Zeichen einschränkst dann ist aktuell der Text falsch. Macht beim Posting vielleicht keinen Sinn, aber wenn das irgendwer für was anderes recycelt, dann ist der Text für ein Zeichen falsch, obwohl die Variable das ansonsten vielleicht hergäbe.

Wenn wir es korrigieren sind wir eine Warnung los.

Geringfügig weniger pathologisch ist TOTAL_POSTS_COUNT: Bei einem neu erstellten Board gibt es genau einen Beitrag. Hier ist der Text dann falsch. Somit haben wir hier einen Sprachfehler, der in jedem neu erstellten Board zu sehen ist.

Die Sucheinträge im ACP sind genauso: Wenn die Indizierung so lahm ist, dass sie nur einen Beitrag pro Durchgang schafft, dann ist der Text falsch.

Ich bin langfristig für aufräumen, so dass unsere Sprachdateiprüfung weniger Fehler enthält, so dass die wichtigen Fehler eher auffallen. Sonst schaut man auf die Liste, sieht nur die üblichen Warnungen und ist der Meinung "och, alles in Ordnung".

**Comment by Crizz0** [comment]
Also "won't fix"?
