### ISSUE TITLE
Change description for recommend update

### ISSUE THREAD

**Issue by canonknipser** [phpbb-de/phpbb-translation#331]
### Additional information:
- Datei "language/de/install.php"
- language-key 'UPDATE_INSTALLATION_EXPLAIN'

**Comment by Crizz0** [comment]
Das muss im Original angepasst und hier übersetzt werden, wenn es bei en/ drin ist.

**Comment by canonknipser** [comment]
Können wir die Language-Strings nicht bei uns separat anpassen? Es wird ja schließlich auch auf unsere Download-Pakete verwiesen.
Klar ist das besser, wenn es für alle angepasst wird.

**Comment by Crizz0** [comment]
Naja, würde könnten natürlich hier alles umschreiben UPDATE_INSTRUCTIONS. aber bessere wäre es die bei phpBB als Improvement zu melden und dort zu patchen und dann hier die Neufassung zu übersetzen.

**Comment by canonknipser** [comment]
Ich hab mal ein Ticket aufgemacht: https://tracker.phpbb.com/browse/PHPBB3-15028
