### ISSUE TITLE
Example-URL vereinheitlichen

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#335]
Aktuell scheinen wir nicht konsequent eine Example-URL zu verwenden, sondern zwischen verschiedenen zu wechseln.

Das sollte auf eine einheitliche, z.B. domain.tld oder example.org vereinheitlicht werden.

Edit:
Umsetzen in "example.org"

**Comment by Philipp-K** [comment]
Und was nehmen wir?

[ ] example.com
[ ] example.org
[ ] example.net
[ ] domain.tld
[ ] domain.example

**Comment by Crizz0** [comment]
example.com

**Comment by Philipp-K** [comment]
Ich würde eher das (neutralere) .net bevorzugen

**Comment by Crizz0** [comment]
Könnte mich auch mit .net anfreunden, da wäre mir allerdings .org lieber.

**Comment by Joyce-Luna** [comment]
Meine Meinung dazu. Ich finde example.com besser, weil dann ein Bezug zur Mutterseite besteht.

**Comment by gn36** [comment]
Inzwischen kann man sich bei top level domains ja auf nix mehr verlassen. Daher scheidet Domain.tld für mich aus. Domain.example ist mir zu lang. Dem Rest stehe ich ziemlich neutral gegenüber, allerdings sind com und org in meinen Augen gebräuchlicher als net.

**Comment by Philipp-K** [comment]
.com ist halt eigentlich für die USA vorgesehen und außerdem kommerziell - da finde ich .net oder .org einfach neutraler. Und ob das nun in der deutschen Übersetzung gleich oder anders ist: da sehe ich keinen praktischen Vorteil drin.

**Comment by gn36** [comment]
Also example.org?

**Comment by Crizz0** [comment]
Fixed via #343
