### ISSUE TITLE
Verwendung "derzeit"

### ISSUE THREAD

**Issue by Philipp-K** [phpbb-de/phpbb-translation#35]
- Ist es notwendig?
- Alternativen: gerade, augenblicklich, im Moment, aktuell, gegenwärtig, momentan

**Comment by Crizz0** [comment]
Also wenn wir das nicht sowieso komplett weglassen wollen, dann bin ich weiterhin für "im Moment". Das ist imho irgendwie gebräuchlicher.

**Comment by Philipp-K** [comment]
Derzeit wird derzeit 57 mal verwendet ;-)

Beispiele:

> Derzeit sind keine ignorierten Mitglieder definiert
> 
> Du hast dein Benutzerkonto derzeit nicht mit diesem Dienst verknüpft.
> 
> Eine Registrierung ist derzeit nicht möglich.

Da finde ich aber "im Moment" etwas zu unpräzise.

Siehe auch
http://forum.wordreference.com/showthread.php?t=2805538&langid=3
http://www.duden.de/rechtschreibung/derzeit

**Comment by gn36** [comment]
Ich denke das hängt alles ein bisschen vom Kontext ab. In einigen Fällen kann das sicher wegfallen. Zum Beispiel würde

> Es sind keine ignorierten Mitglieder definiert.

sicherlich ebenfalls möglich sein, ebenso

> Du hast dein Benutzerkonto nicht mit diesem Dienst verknüpft.

Bei der Registrierung ist die Frage nicht so einfach. "Derzeit" suggeriert einen temporären Zustand, der möglicherweise gar nicht zutrifft. Vielleicht hat der Admin aber die Registrierung auch nur temporär deaktiviert. Da man bei vielen Internetdiensten auf ähnliche Formulierungen trifft und die meisten Foren wohl Registrierungen zulassen dürften und die Abschaltung somit nur temporär nutzen würde ich es hier drin lassen.

**Comment by Philipp-K** [comment]
- gerade: konnte komplett eliminiert werden
- augenblicklich: bislang nicht verwendet
- im Moment: bislang nicht verwendet
- aktuell: kommt recht häufig vor - siehe getrennter Kommentar
- gegenwärtig: konnte komplett eliminiert werden
- momentan: bislang nicht verwendet

**Comment by Philipp-K** [comment]
**Aktuell:**

Bleibt:
- aktuelle Version
- aktuelle Einstellung
- aktueller Wert (in php.ini) - siehe aber unten
- aktuelle Zeit
- Aktuelle Tätigkeit (hat da jemand was besseres?)
- aktueller Vorgang
- aktuelle Zeitzone

Ersetzt durch derzeit:
- Aktueller Wert (bei Fehler in der Dateistatistik): die angezeigten Werte sind ja hier gerade nicht aktuell
- Aktueller Beitrag (Überschreiben beim Laden eines Entwurfs)
- Aktuelles Thema (CURRENT_TOPIC) - wo wird das überhaupt verwendet?
- Aktuelles Bild
- Aktuelles Passwort
  (Hat alles imho nichts mit Aktualität zu tun)

Ersetzt durch aktiv:
- aktuellen Sperren (Banning)

Ersetzt durch jeweilige:
- ist ein Formular bei Gästen nur für die aktuelle Sitzung gültig

Ersetzt durch vorhandene:
- aktuellen globalen Bekanntmachungen (Update)

**Comment by Philipp-K** [comment]
**Derzeit:**

Habe ich entfernt oder durch "im Moment" oder "Momentan" ersetzt. (Momentan passt vor allem da besser, wo es sich nicht auf einen ganz eng begrenzten Moment bezieht)

Ausnahmen:
- Derzeitiger Wert (s.o.)
- Derzeit ausgewählt (Zeitzonen)
- Derzeitige Mitglieder
