### ISSUE TITLE
Abstimmungen vs. abgegebene Stimmen

### ISSUE THREAD

**Issue by gn36** [phpbb-de/phpbb-translation#357]
## Template for Issues on phpBB.de Translation

Source: https://www.phpbb.com/customise/db/translation/german_casual_honorifics/support/topic/190886

### Actual wording
"Abstimmungen insgesamt" and the number of cast votes.
However "Abstimmungen insgesamt" translates to "number of polls".

### Expected wording
The correct translation for the number of cast votes would be "Insgesamt abgegebene Stimmen"

### phpBB version
3.2.1

### Affected language package (de or de_x_sie)
de, de_x_sie

### Link to the page in the board 
Example: https://www.phpbb.de/community/viewtopic.php?f=79&t=200158

**Comment by Crizz0** [comment]
Wäre ich dafür, dass klingt schon besser.
