### ISSUE TITLE
Doppelter Doppelpunkt: lassen oder entfernen

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#362]
Siehe: https://www.phpbb.de/community/viewtopic.php?f=142&t=233389

**Comment by Philipp-K** [comment]
Ist meiner Ansicht ein Design-Element und sollte daher so bleiben

**Comment by Crizz0** [comment]
Ja, ist auch ein Designelement, um da einen größeren "Abstand" zu bauen.
