### ISSUE TITLE
Datenschutzrichtlinie oder Datenschutzerklärung

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#363]
Von: https://www.phpbb.de/community/viewtopic.php?f=157&t=241760

Aktuell wird überall "Datenschutzrichtlinie" verwendet. 

Vorschlag wäre, es nach "Datenschutzerklärung" umzubenennen, was mMn ein wenig eindeutiger ist. 

Ich würde es daher in "Datenschutzerklärung" umbenennen. Einwände?

**Comment by Philipp-K** [comment]
Datenschutzerklärung hat sich eigentlich etabliert - daher OK
