### ISSUE TITLE
UCP -> Einstellungen > Nachrichten erstellen: ungenau übersetzt?

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#381]
Siehe: https://www.phpbb.com/customise/db/translation/german_formal_honorifics/support/topic/201636?p=678121#p678121 
\language\de_x_sie\ucp.php bzw. \language\de\ucp.php
`
'UCP_PREFS_POST'			=> 'Nachrichten erstellen',`

Unter: ucp.php?i=ucp_prefs&mode=post (Persönlicher Bereich > Einstellungen > Nachrichten erstellen), wird "Edit posting defaults" zu "Nachrichten erstellen" übersetzt. 

In den Optionen kann man das Standardverhalten der Checkboxes im Posting-Editor einstellen:
- BBCode, Smilies, Signatur und Antworten informieren

Die Übersetzung ist möglicherweise ungenau. 

Mögliche Alternativen für "Edit posting defaults" anstelle von "Nachrichten erstellen"
- Beitragsoptionen ändern
- Beitragseinstellungen
- Beitragsvoreinstellungen ändern
- etc.

**Comment by Crizz0** [comment]
Ich bin für **Beitragsoptionen ändern** , da der Tab unter dem Beitragseditor **Optionen** heißt, passt das imho am besten.

**Comment by canonknipser** [comment]
Kein Einspruch meinerseits ;)
