### ISSUE TITLE
Updates 3.2.8 to 3.3.0-b1

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-translation#393]
Update für phpBB 3.3.0-b1 von 3.2.8 aus gesehen: 
https://gist.github.com/marc1706/e816f7d3d7162c5befb2a1c8155db220

**Comment by gn36** [comment]
Das ist ja ziemlich übersichtlich :-)

**Comment by Crizz0** [comment]
Joah, das ist auch nur so ein Soft-Update, was primär das Ziel hat Kompatibilität mit PHP 7.3 herzustellen. 

Also nur zu! 👍

**Comment by gn36** [comment]
Ok :-)

**Comment by gn36** [comment]
Ein paar englische Originale sind irgendwie etwas fragwürdig, ich glaube nicht dass die Englischen Originaltexte z.B. zum Thema FILESYSTEM wirklich richtig sind (z.B. "touch": Normalerweise legt dass eine fehlende Datei an oder modifiziert den Zeitstempel wenn sie existiert, laut Symfony Doku ist das auch hier der Fall, aber die Übersetzung sagt was völlig anderes), oder sie helfen dem User nicht weiter ("dump" im Sinne von Löschen (falsch laut Symfony Doku) oder "dump" im Sinne von Daten hineinwerfen (das ist hier gemeint)).
Ein paar Links wurden auch noch nicht von 3.2 auf 3.3 umgestellt :-), da kommt also sicher auch noch was (allein in install.php gibt's noch mindestens 10 weitere stellen mit 3.2 drin)

**Comment by Crizz0** [comment]
Dump im Sinne von "Datei ablegen", dann vermutlich eher.

**Comment by Crizz0** [comment]
Kannst du mal hier reinschreiben, welche du ändern würdest: https://tracker.phpbb.com/browse/PHPBB3-16230 ?

**Comment by gn36** [comment]
Erledigt. Reviewst du meinen PR trotzdem?

**Comment by Crizz0** [comment]
Ja, mach ich.

**Comment by Crizz0** [comment]
Close via #394
