### ISSUE TITLE
`Beitrag "abc" von UserA` vs. `Beitrag "abc" von Autor UserA`

### ISSUE THREAD

**Issue by nickvergessen** [phpbb-de/phpbb-translation#40]
https://github.com/phpbb-de/phpbb-translation/pull/39#discussion_r12503272

**Comment by Philipp-K** [comment]
Ich hatte es erst ohne "Autor" versucht. Das wäre dann zum Beispiel:
_Freigabe von Beitrag „Testbeitrag“ von „User“ verweigert_

Problem bei der Lösung: der Bezug von "von" ist nicht klar. Vom Text her könnte es sowohl heißen, dass der Beitrag, den "User" erstellt hat, nicht freigegeben wurde - aber auch, dass der Nutzer "User" die Freigabe des Beitrages verweigert hat.

Man kann sicherlich noch anführen, dass es dem erfahrenen phpBB-Nutzer klar sein müsste, dass der User, der die Aktion durchgeführt hat, an anderer Stelle erwähnt wird - aber ich weiß nicht, ob das auch beim Otto-Normal-phpBB-ler der Fall ist

**Comment by nickvergessen** [comment]
Doch ist schon klar, weil links von dem Satz steht, wer die Aktion ausgeführt hat?

**Comment by nickvergessen** [comment]
sonst "Der Beitrag xyz von abc wurde ..."

**Comment by Crizz0** [comment]
Was ist mir sowas? 

"Freigabe des Beitrags „%1$s“ wurde von „%3$s“ aus folgendem Grund verweigert: %2$s"

**Comment by nickvergessen** [comment]
Der moderator name ist nicht in den log daten enthalten

**Comment by Philipp-K** [comment]
So sieht das derzeit aus:
![mcp_log](https://cloud.githubusercontent.com/assets/845541/2939051/f3ca0658-d933-11e3-9e7f-6c28269c025b.jpg)
