### ISSUE TITLE
Change: reset password

### ISSUE THREAD

**Issue by c0ball** [phpbb-de/phpbb-translation#424]
## Template for Issues on phpBB.de Translation

This template will help you to give us the required information to fix the bug or integrated the improvement you'll report to us.

### Actual wording

Zurücksetzen

### Expected wording
Eingabe leeren / Eingabe löschen

### phpBB version
3.3.2
### Affected language package (de or de_x_sie)
de

### Additional information:
/app.php/user/forgot_password

Please change the german translation of the reset button on the password reset page. I receive so many email that they pressed on the "reset" button but did not received a new password which is so annyoing

**Comment by Crizz0** [comment]
Das ist so nicht umsetzbar, da man das nicht nur auf der "Passwort vergessen"-Seite ändern kann, sondern nur global:

Das Template sieht so aus: https://github.com/phpbb/phpbb/blob/5a55891d060ecd4e9011146b68bc1366ac663d90/phpBB/styles/prosilver/template/ucp_reset_password.html#L39 

Der Key: 	`'RESET'						=> 'Reset',` von https://github.com/phpbb/phpbb/blob/5a55891d060ecd4e9011146b68bc1366ac663d90/phpBB/language/en/common.php#L671 

Man könnte den übersetzen als "nullen" oder "löschen" oder "auf null stellen". Wobei das an vielen Stellen echt nicht gut klingt, mal von "löschen" abgesehen. Wobei es halt im Original kein "delete" ist. 

Was mich halt wundert, dass du das Problem ist deinen Nutzern hast, wegen "zurücksetzen" auf der "Passwort zurücksetzen" wohin gegen die mir bekannte englische Community auf der Seite "Reset password" mit dem Button "Reset" gar keine Probleme hat.

**Comment by c0ball** [comment]
Ich denke mal, dass das auch damit zusammenhängt, dass mein Forum größtenteils von Nutzern 50+ genutzt wird und da nicht so das technische Verständnis vorhanden ist. 
Da der Button ja nur bei Formularfeldern erscheint fände ich _Eingabe zurücksetzen_ oder _Eingabe leeren_ oder _löschen_ besser ;) bzw verständlicher. Wobei ich ja meiner Meinung nach mal anmerken muss, dass ich den ganzen Button eh überflüssig finde.

**Comment by Crizz0** [comment]
> Wobei ich ja meiner Meinung nach mal anmerken muss, dass ich den ganzen Button eh überflüssig finde.

Ja, da könnte man eigentlich mal phpBB 3.3 komplett patchen und diesen Button einfach weghauen, den braucht man imho quasi nie.

**Comment by c0ball** [comment]
Da du ja meinen phpBB Post entdeckt hast, kann ich das hier ja schließen

**Comment by Crizz0** [comment]
Ich hab dich ja hier her verwiesen. Aber wenn wir hier was ändern, braucht man das Issue als Bezugspunkt. 

Mal schauen, was die anderen meinen.

**Comment by c0ball** [comment]
Achso ups😂, ist wohl schon etwas spät😅

**Comment by gn36** [comment]
Wird das noch sonstwo eingesetzt außer bei dem Rücksetz-Button in Formularen? Wenn nein könnten wir es einfach deutlich ausführlicher machen mit "Eingabeformular zurücksetzen".

"Eingabe löschen" fände ich aber auch ok, "Eingabe leeren" würde ich "Eingabeformular leeren" draus machen.

Ich habe eben mal danach gesucht und nichts gefunden, allerdings hat sich inzwischen auch die Syntax geändert seit ich das letzte Mal was in Templates gesucht habe und vielleicht habe ich nicht alle Fälle abgedeckt...

Ich finde aber auch, dass der Button insgesamt weg kann. Ich habe den immer höchstens aus versehen benutzt und war über das Ergebnis verärgert.

**Comment by c0ball** [comment]
Wie gesagt, ich fände eine Entfernung des Buttons am sinnvollsten.

**Comment by gn36** [comment]
Dafür braucht's dann allerdings ein Ticket bei phpbb.com. 
Zu dem Thema gabs schon vor Jahren mal Anregungen, wurde damals aber nicht gemacht, vermutlich weil zu viel auf einmal drin ist: https://tracker.phpbb.com/browse/PHPBB3-1787

Ich habe mal ein Ticket erstellt: https://tracker.phpbb.com/browse/PHPBB3-16660
Abhängig vom Ergebnis wird der ganze Lang Key rausfliegen, wenn der Button weg ist. Unabhängig davon sollten wir aber hier denke ich entscheiden was wir damit machen, wenn es eben nicht entfernt werden sollte.

**Comment by c0ball** [comment]
Also wenn es nicht entfernt werden sollte wäre ich für deinen Vorschlag das Feld mit "Eingabe löschen" zu übersetzen.

**Comment by Crizz0** [comment]
Habe mal einen PullRequest erstellt, mal sehen, ob er so akzeptiert wird.

**Comment by Crizz0** [comment]
Der PullRequest wurde angenommen, der Button ist dort und an vielen anderen MCP und UCP Seiten somit entfernt worden. Ab Version phpBB 3.3.4...
