### ISSUE TITLE
Neuster Beitrag / jüngster Beitrag

### ISSUE THREAD

**Issue by Philipp-K** [phpbb-de/phpbb-translation#433]
Da bin ich bei den Anpassungen der E-Mail-Templates drüber gestolpert:
Aktuell verwenden wir bei Themen und Beiträgen immer "neuester Beitrag" etc. In der Konstellation wäre auch "jüngster Beitrag" möglich, was m.E. etwas schöner klingt - insb. im Plural (die neuesten Beiträge vs. die jüngsten Beiträge).

Meinungen?

**Comment by Crizz0** [comment]
Gefällt mir ehrlich gesagt nicht besser, würde es bei "neuste" lassen.

**Comment by LehrlingBeate** [comment]
Hallo, 
"jüngster" ist aus meiner Sicht eher veraltet und ich bin mir nicht sicher, ob die Jugend mit dem Begriff noch etwas anfangen kann.

**Comment by Philipp-K** [comment]
Dann lassen wir das so - allerdings ist mir noch aufgefallen, dass wir das an einer Stelle vereinheitlichen müssen
