### ISSUE TITLE
Freigabe erfordern / erwarten

### ISSUE THREAD

**Issue by Philipp-K** [phpbb-de/phpbb-translation#434]
Und noch was aus den E-Mails:

Bislang haben wir immer "Beitrag erwartet (deine) Freigabe" - hier fände ich "Beitrag erfordert (deine) Freigabe" eine bessere Alternative.

**Comment by Crizz0** [comment]
ich hätte noch:
"muss freigegeben werden" im Angebot. Das klingt imho ein wenig umgangssprachlicher.

**Comment by LehrlingBeate** [comment]
Hallo,
ich schließe mich Crizzo an: "muss freigegeben werden" klingt für mich am neutralsten.
