### ISSUE TITLE
"Smileys" spelled wrong

### ISSUE THREAD

**Issue by domivogt** [phpbb-de/phpbb-translation#450]
The translation of the English word "smilies" (plural) to German is wrong.

### Actual wording

Smilies

### Expected wording

Smileys

### phpBB version

3.3.7

### Affected language package (de or de_x_sie)

de and de_x_sie

### Link to the page in the board 

I guess it's universally spelled wrong, allover the place.

### Additional information:

Check German grammar:
https://www.duden.de/rechtschreibung/Smiley

**Comment by Crizz0** [comment]
Doppelt.
