### ISSUE TITLE
-Smileys- spelled wrong

### ISSUE THREAD

**Issue by domivogt** [phpbb-de/phpbb-translation#451]
The translation of the English word "smilies" (plural) to German is wrong.

### Actual wording

Smilies

### Expected wording

Smileys

### phpBB version

3.3.7

### Affected language package (de or de_x_sie)

de and de_x_sie

### Link to the page in the board 

I guess it's universally spelled wrong, allover the place.

### Additional information:

Check German grammar:
https://www.duden.de/rechtschreibung/Smiley

**Comment by domivogt** [comment]
Affected files:

$ rgrep -l "Smilies" .
./language/en/help/faq.php
./language/en/acp/posting.php
./language/en/acp/common.php
./language/en/acp/board.php
./language/de_x_sie/ucp.php
./language/de_x_sie/posting.php
./language/de_x_sie/install.php
./language/de_x_sie/help/faq.php
./language/de_x_sie/acp/posting.php
./language/de_x_sie/acp/permissions_phpbb.php
./language/de_x_sie/acp/common.php
./language/de_x_sie/acp/board.php
./language/de/ucp.php
./language/de/posting.php
./language/de/install.php
./language/de/help/faq.php
./language/de/acp/posting.php
./language/de/acp/permissions_phpbb.php
./language/de/acp/common.php
./language/de/acp/board.php

You may also want to grep for "smilies" (with lowercase 's').

**Comment by LukeWCS** [comment]
@domivogt 

Danke für die Meldung.

**Comment by Crizz0** [comment]
Fixed
