### ISSUE TITLE
FILES_STATS_WRONG is missing arguments

### ISSUE THREAD

**Issue by nickvergessen** [phpbb-de/phpbb-translation#47]
```
Key “FILES_STATS_WRONG” in file “language/de/acp/attachments.php” should have “3” string arguments, but has “1”
```

English:

> Your file statistics are likely inaccurate and need to be resynchronised. Actual values: number of attachments = %1$d, total size of attachments = %2$s.<br />Click %3$shere%4$s to resynchronise them.

German:

>  Deine Datei-Statistik ist vermutlich fehlerhaft und muss resynchronisiert werden. Aktuelle Werte: Anzahl von Dateianhängen = %1$d, Gesamtgröße der Dateianhänge = %2$s.

**Comment by nickvergessen** [comment]
Sollte das Ergebnis der "Hier klicken"-Diskussion abwarten.

**Comment by Philipp-K** [comment]
Ich würde das gleich "richtig" machen

**Comment by nickvergessen** [comment]
Jo würde ich auch sagen
