### ISSUE TITLE
URL in help_bbcode.php was not updated

### ISSUE THREAD

**Issue by nickvergessen** [phpbb-de/phpbb-translation#51]
The URL was changed from google.com to phpbb.com:
https://github.com/phpbb/phpbb/commit/02f739e0e7a73ba703f4403d9e20bfbc8cc8de66

The german language now uses the updated image (phpBB logo) but still links to google.de

**Comment by Philipp-K** [comment]
Linken wir da auf .de oder .com?

**Comment by nickvergessen** [comment]
Es ist das .com Logo, dann sollte es auch dahin verlinken?

**Comment by Philipp-K** [comment]
Ist ein Argument
