### ISSUE TITLE
"Diese Sprachdateien für phpBB3 unterliegen der GPL (siehe LICENSE)."

### ISSUE THREAD

**Issue by bantu** [phpbb-de/phpbb-translation#52]
- Es gibt keine LICENSE-Datei.
- Sollte wohl einfach nur phpBB heißen.

**Comment by nickvergessen** [comment]
Die Datei heißt auf einmal license.txt
Das hab ich wohl beim Import kaputt gemacht.

**Comment by Philipp-K** [comment]
Dann weisen wir das einfach mal zu :)
