### ISSUE TITLE
Anpassung/Prüfung der Weiterleitungen (go-Links)

### ISSUE THREAD

**Issue by Philipp-K** [phpbb-de/phpbb-translation#77]
Die verwendeten Quicklinks sollten überprüft und ggf. angepasst werden, da wir ja in der Zwischenzeit eigene Foren für 3.1 haben

**Comment by Crizz0** [comment]
So, also ich bin dann mal dabei:
https://www.phpbb.de/go/3/dokumentation <-- den brauchen wir wohl mal als 3.1 Version oder ändern wir die Übersichtsseite: https://www.phpbb.de/support/doku/ entsprechend?

**Comment by Crizz0** [comment]
Dann brauchen wir einen Quicklink wie: https://www.phpbb.de/go/3/supportforum für 3.1 und zwar nach hier: https://www.phpbb.de/community/viewforum.php?f=145

**Comment by Crizz0** [comment]
https://www.phpbb.de/go/3/schnellstart --> 3.1 oder anpassen?

**Comment by Crizz0** [comment]
ttps://www.phpbb.de/go/3/konvertierung --> 3.1 und zu diesem Forum: Forum: https://www.phpbb.de/community/viewforum.php?f=146

**Comment by Crizz0** [comment]
Diese: https://www.phpbb.de/go/3/berechtigungen
kann mMn bleiben, da hat sich nichts Besonderes geändert.

**Comment by Crizz0** [comment]
Kein Quicklink, aber trotzdem verwendet: https://www.phpbb.com/support/documentation/3.0/ sollte dann natürlich auf 3.1 Doku verweisen, sofern vorhanden.

**Comment by Crizz0** [comment]
https://www.phpbb.de/go/3/styles --> 3.1 und Forum: https://www.phpbb.de/community/viewforum.php?f=152

**Comment by Crizz0** [comment]
https://www.phpbb.de/go/3/ersteschritte --> den brauchen wir für 3.1 auch und zwar als deutlich angepasste Version.

**Comment by Crizz0** [comment]
https://www.phpbb.de/go/3/downloads --> wie machen wir das?

**Comment by gn36** [comment]
Ich denke wir sollten das einheitlich handhaben - entweder wir legen für alles einen 3.1 Link an, oder wir schauen, dass alle Links auf eine Seite zeigen, die sowohl für 3.0 als auch für 3.1 nutzbar ist. 

Gerade mit den Support-Foren ist es aber vermutlich sinnvoll, eigene Links anzulegen - ob die übrigen dann auf die gleiche Seite zeigen wie die "3" Version oder nicht, ist ja egal, so ein riesiger Overhead ist das ja nicht.

**Comment by Crizz0** [comment]
Das ändert ja jetzt nichts groß, ich hab ja nur bei einem Link eine wirkliche "kann so bleiben" vorgeschlagen. 

Wer kann denn neue Quicklinks anlegen?

**Comment by Philipp-K** [comment]
Einer mit SSH-Zugriff auf den Server :-)

**Comment by Philipp-K** [comment]
Und vielleicht vor RC5 :-)

**Comment by nickvergessen** [comment]
Baut die Links einfach ein und fertig.
