### ISSUE TITLE
Formulierungsänderung "nach Fehlern untersuchen"

### ISSUE THREAD

**Issue by gn36** [phpbb-de/phpbb-translation#83]
In der language/de_x_sie/migrator.php bzw. analog auch language/de/migrator.php:
https://github.com/phpbb-de/phpbb-translation/blob/develop-ascraeus/language/de/migrator.php#L50

`Sie sollten Ihr Board jedoch nach möglichen Fehlern untersuchen.`

In meinen Augen sollte das besser:
`Sie sollten Ihr Board jedoch auf mögliche Fehler hin untersuchen.`
oder 
`Sie sollten Ihr Board jedoch nach möglichen Fehlern durchsuchen.`
heißen.

**Comment by nickvergessen** [comment]
Gibts da noch mehr kontext?

**Comment by gn36** [comment]
Der volle Text lautet (Du Version, aber die Sie Version ist praktisch identisch): 

> Während der Anforderung ist etwas falsch gelaufen und eine Ausnahme ist aufgetreten. Die Änderungen, die vor dem Fehler durchgeführt wurden, wurden so weit wie möglich rückgängig gemacht. Du solltest dein Board jedoch nach möglichen Fehlern untersuchen.

**Comment by Philipp-K** [comment]
Im Englischen:

> Something went wrong during the request and an exception was thrown. The changes made before the error occurred were reversed to the best of our abilities, but you should check the board for errors.

Ich wäre wohl eher für eine etwas freiere Interpretation:

> Du solltest jedoch prüfen, ob dein Board fehlerfrei funktioniert.

**Comment by nickvergessen** [comment]
Jo klingt auch gut @Philipp-K 

BTW Anforderung ist wohl eher als "Datenbank request" also Anfrage zu verstehen?

**Comment by Philipp-K** [comment]
Wie wäre es damit (tritt bei der DB-Anpassung für Extensions auf):

> Während der Anpassung der Datenbank ist etwas falsch gelaufen und eine Ausnahme aufgetreten. Die Änderungen, die vor dem Fehler durchgeführt wurden, wurden so weit wie möglich rückgängig gemacht. Du solltest jedoch prüfen, ob dein Board fehlerfrei funktioniert.

**Comment by nickvergessen** [comment]
Jetzt noch Fehler anstatt Ausnahme und ic find es passt. Exception ist code Logik und nicht als Ausnahme, aka tritt nur einmal auf, zu verstehen.

**Comment by Philipp-K** [comment]
> Während der Anpassung der Datenbank ist etwas falsch gelaufen und ein Fehler aufgetreten. Die Änderungen, die vor dem Fehler durchgeführt wurden, wurden so weit wie möglich rückgängig gemacht. Du solltest jedoch prüfen, ob dein Board fehlerfrei funktioniert.

**Comment by gn36** [comment]
Hört sich gut an.
