### ISSUE TITLE
[viewtopic.php] MAX_OPTIONS_SELECT noch nicht angepasst

### ISSUE THREAD

**Issue by mungo** [phpbb-de/phpbb-translation#94]
```
'MAX_OPTIONS_SELECT'        => array(
```
-      1   => '#Du kannst <strong>eine</strong> Option auswählen',
-      2   => '#Du kannst bis zu <strong>%d</strong> Optionen auswählen',
-      1   => 'Du kannst <strong>eine</strong> Option auswählen',
-      2   => 'Du kannst bis zu <strong>%d</strong> Optionen auswählen',
  ),

Hier wurde "Du kannst" übersehen.

**Comment by Philipp-K** [comment]
Behoben durch #97
