### ISSUE TITLE
[permissions_phpbb.php] ACL_F_POSTCOUNT Verwendung von "greift"

### ISSUE THREAD

**Issue by nickvergessen** [phpbb-de/phpbb-translation#96]
`Beitrags-Zähler wird erhöht<br /><em>Bitte beachte, dass diese Einstellung nur für neue Beiträge greift.</em>`

Vllt sowas wie `... nur neue Beiträge betrifft.`?

**Comment by Philipp-K** [comment]
Original:

> Increment post counter<br /><em>Please note that this setting only affects new posts.</em>

Eigentlich finde ich die aktuelle Form recht gut

**Comment by gn36** [comment]
Betrifft passt imho nicht ganz, weil es an den Beiträgen ja nichts ändert.

**Comment by Philipp-K** [comment]
Wie wäre es mit

> Bitte beachte, dass nur neue Beiträge berücksichtigt werden

?

**Comment by Philipp-K** [comment]
Meinungen?

**Comment by nickvergessen** [comment]
Klingt besser als das "greift"

**Comment by Crizz0** [comment]
Japp, finde ich auch. :+1:

**Comment by gn36** [comment]
Eigentlich berücksichtigt die Einstellung imho nichts, sondern bei der Erstellung von Beiträgen wird die Einstellung berücksichtigt. Also wäre ich eher für sowas wie

> Bitte beachte, dass Änderungen an dieser Einstellung nur bei neuen Beiträgen berücksichtigt werden.

Alternativ

> Bitte beachte, dass diese Einstellung nur bei neuen Beiträgen berücksichtigt wird und sich nicht auf vorhandene Beiträge auswirkt.

In meinen Augen passt "greift" aber immer noch besser.

**Comment by Philipp-K** [comment]
Anderer Vorschlag:

> Bitte beachte, dass diese Einstellung nur die Wirkung neuer Beiträge auf den Beitrags-Zähler betrifft

**Comment by gn36** [comment]
Wäre in meinen Augen ok, allerdings muss man den Satz mehrfach lesen.

> Bitte beachte, dass diese Einstellung nur bei neuen Beiträgen berücksichtigt wird und nur deren Wirkung auf den Beitrags-Zähler beeinflusst.

Oder bei deinem Vorschlag einfach "betrifft" durch "beeinflusst" ersetzen:

> Bitte beachte, dass diese Einstellung nur die Wirkung neuer Beiträge auf den Beitrags-Zähler beeinflusst.

**Comment by Philipp-K** [comment]
Eine kürzere Fassung wäre mir lieber - das Original ist auch nur knapp gehalten

**Comment by Philipp-K** [comment]
Mal ein paar Versuche:
- Diese Einstellung wirkt nur auf neu erstelle Beiträge
- Diese Einstellung hat keine Auswirkung auf bereits bestehende Beiträge
- Diese Einstellung ändert nicht die Berücksichtigung bestehender Beiträge im Beitrags-Zähler
- Bitte beachte, dass diese Einstellung nur auf neue Beiträge wirkt
- Bitte beachte, dass diese Einstellung nur auf neu erstellte Beiträge wirkt
  Sucht euch eins aus :)

**Comment by gn36** [comment]
Hm notfalls wäre ich eher für eine der folgenden Varianten:
- Der Beitrags-Zähler berücksichtigt diese Einstellung nur für neue Beiträge.
- Im Beitrags-Zähler wird diese Einstellung nur bei neuen Beiträgen berücksichtigt.
- Diese Einstellung wird im Beitrags-Zähler nur bei neuen Beiträgen berücksichtigt.

Die letzte Variante passt wohl am besten zu deinen Vorschlägen.

**Comment by Philipp-K** [comment]
Greifen wir das Thema nochmals auf.

Im Englischen: Please note that this setting only affects new posts.
affect bedeutet ja "beeinflussen, wirken" (weniger passende Interpretationen gibt's bei LEO)

Ich würde daraus wohl
Diese Einstellung wirkt nur für neu erstellte Beiträge
machen.

**Comment by Philipp-K** [comment]
Passt der neue Vorschlag oder hat jemand noch andere Wünsche?

**Comment by Philipp-K** [comment]
> Bitte beachte, dass diese Einstellung nur für neu erstellte Beiträge wirkt.
> hört sich komisch an. Daher
> Bitte beachte, dass diese Einstellung nur bei neu erstellten Beiträgen wirkt.
