### ISSUE TITLE
[acp/board.php] OAuth Key und Secret

### ISSUE THREAD

**Issue by mungo** [phpbb-de/phpbb-translation#98]
Bei AUTH_PROVIDER_OAUTH_EXPLAIN haben wir "Key <em>(Schlüssel)</em>" und Secret <em>(Geheimnis)</em> geschrieben. Vielleicht sollten wir es bei AUTH_PROVIDER_OAUTH_ERROR_ELEMENT_MISSING auch machen.

**Comment by Philipp-K** [comment]
Die Idee war eigentlich, es einmal in der einführenden Erklärung zu beschreiben und ansonsten immer nur die englischen Begriffe zu verwenden, da diese in OAuth so definiert sind

**Comment by nickvergessen** [comment]
Was davon sehen eigentlich End-User?

**Comment by Philipp-K** [comment]
Vermutlich Garnichts - wenn ich das richtig sehe

**Comment by Philipp-K** [comment]
Sollen wir jetzt AUTH_PROVIDER_OAUTH_ERROR_ELEMENT_MISSING anpassen oder reicht die einmalige Erläuterung in AUTH_PROVIDER_OAUTH_EXPLAIN? Ich würde letzteres vorziehen.

**Comment by gn36** [comment]
Nur ein Mal erklären ist imho besser.

**Comment by Philipp-K** [comment]
Dann lassen wir das so
