### ISSUE TITLE
Add build task to build install/update packages

### ISSUE THREAD

**Issue by nickvergessen** [phpbb-de/phpbb-translation#99]
Es gibt hier 2 Möglichkeiten die beide jeweils eigene Nachteile haben:
1. Wir legen einen phpBB-Fork an, paken dort immer das aktuelle Sprachpaket rein, legen dann den Tag an und benutzen das Build-Skript von phpBB an sich.
   - Vorteil: wir können müssen nicht im Paket rumbasteln, gelöschte Dateien werden automatisch mit gelistet, das Build-Skript macht die Pakete so klein wie möglich (nur geänderte Dateien etc.). Wir könnten auch Daily-Builds veröffentlichen.
   - Nachteil: wir brauchen den Fork, müssen das Build-Skript minimal anpassen (Dateinamen auf *-deutsch ändern) und sollten dann automatisch phpbb-translation da rein kopieren. Bei einem Release muss in beidem Repositories ein Tag angelegt werden.
2. Wir laden die Pakete von https://download.phpbb.com/pub/release/3.1/ nach dem Release runter und manipulieren die dann, wie es bisher auch der Fall war.
   - Vorteil: kein Repository und kopieren von phpbb-translation
   - Nachteil: Pakete bauen braucht Internetverbindung, hacken nötig um Liste der geänderten und gelöschten Dateien anzupassen. Nur für phpBB Releases möglich.

**Comment by nickvergessen** [comment]
Meinungen? @bantu @mungo @gn36 @Crizz0 @Philipp-K

**Comment by Crizz0** [comment]
@1.: Das klingt auch nach viel manueller Arbeit, geht das denn schneller als 2.? 
"Wir könnten auch Daily-Builds veröffentlichen." <-- wie bamboo passend? Dazu müssten wir aber auch immer die Änderungen, sofern notwendig, zeitnah umsetzen. 

@2.: "Nur für phpBB Releases möglich." <-- wofür könnten/sollten wir es noch nutzen wollen?

**Comment by nickvergessen** [comment]
bzgl 2. Daily builds ;)

Die manuelle Arbeit bei 1. ist einmalig. Bei 2. muss man sie jedesmal machen wenn man neue Pakete baut. Also unter umständen mehrfach pro Release

**Comment by Crizz0** [comment]
Dann fände ich 1. irgendwie praktischer.

**Comment by gn36** [comment]
Dito

**Comment by nickvergessen** [comment]
https://www.phpbb.de/community/viewtopic.php?f=63&t=231813
